/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softidea.www.public_access.login_user;

import com.sun.awt.AWTUtilities;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author deepalsuranga
 */
public class first_loadingWindow extends javax.swing.JFrame {

    /**
     * Creates new form first_loadingWindow
     */
    public first_loadingWindow() {
        initComponents();
        
        
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            jLabel2.setIcon(null);
            jLabel3.setIcon(null);
            jLabel4.setIcon(null);
            jLabel5.setIcon(null);
            jLabel6.setIcon(null);
            
        } catch (Exception ex) {
        }
        try {
            AWTUtilities.setWindowOpaque(this, false);
        } catch (Exception e) {
        }

        loadingPage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        softidea = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 132, 3));

        softidea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        softidea.setForeground(new java.awt.Color(255, 255, 255));
        softidea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        softidea.setText("Softidea Creation (Pvt) Ltd.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(softidea, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(softidea, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 500, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 60, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 60, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading.gif"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 60, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 60, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 60, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading_window.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        setSize(new java.awt.Dimension(500, 314));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(first_loadingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(first_loadingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(first_loadingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(first_loadingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new first_loadingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel softidea;
    // End of variables declaration//GEN-END:variables

    private void loadingPage() {

        try {
            new Thread(new Runnable() {

                public void run() {
                    try {
                        for (int i = 0; i < 102; i++) {

                            if (i == 20) {
                                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading.gif")));
                            }
                            if (i == 40) {
                                jLabel2.setIcon(null);
                                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading.gif")));
                            }
                            if (i == 60) {
                                jLabel2.setIcon(null);
                                jLabel3.setIcon(null);
                                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading.gif")));
                            }
                            if (i == 80) {
                                jLabel2.setIcon(null);
                                jLabel3.setIcon(null);
                                jLabel4.setIcon(null);
                                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading.gif")));
                            }
                            if (i == 100) {
                                jLabel2.setIcon(null);
                                jLabel3.setIcon(null);
                                jLabel4.setIcon(null);
                                jLabel5.setIcon(null);
                                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/loading.gif")));
                            }

                            if (i == 101) {
                                user_login user = new user_login();
                                user.setVisible(true);
                                first_loadingWindow.this.dispose();
                            }
                            Thread.sleep(50);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
        } catch (Exception e) {
        }

    }

    
    
}
