/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softidea.www.public_access.login_user;

import com.softidea.www.private_access.adminstrator.Admin_workArea;
import com.softidea.www.public_connection.MC_DB;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author deepalsuranga
 */
public class user_login extends javax.swing.JFrame {

    String user_type;

    /**
     * Creates new form user_login
     */
    public user_login() {

        initComponents();
         try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        setAlwaysOnTop(true);
        tf_username.setRequestFocusEnabled(true);
        tf_username.grabFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_locklogin = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 200, 83));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 461, 400, -1));

        jPanel2.setBackground(new java.awt.Color(0, 200, 83));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 372, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        jPanel3.setBackground(new java.awt.Color(65, 65, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel8MouseMoved(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 40, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        jButton1.setText("Login Here");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 250, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        tf_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_username.setForeground(new java.awt.Color(0, 150, 136));
        tf_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_username.setBorder(null);
        tf_username.setMaximumSize(new java.awt.Dimension(300, 40));
        tf_username.setMinimumSize(new java.awt.Dimension(300, 40));
        tf_username.setPreferredSize(new java.awt.Dimension(300, 40));
        tf_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_usernameMouseClicked(evt);
            }
        });
        tf_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_usernameKeyReleased(evt);
            }
        });
        jPanel3.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 300, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/Logo150.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, 150));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Forget Password?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 100, -1));

        lb_locklogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_locklogin.setForeground(new java.awt.Color(255, 255, 255));
        lb_locklogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_locklogin.setText("LOGIN SYSTEM");
        lb_locklogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_locklogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(lb_locklogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 300, 40));

        pf_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pf_password.setForeground(new java.awt.Color(0, 150, 136));
        pf_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pf_password.setBorder(null);
        pf_password.setMaximumSize(new java.awt.Dimension(300, 40));
        pf_password.setMinimumSize(new java.awt.Dimension(300, 40));
        pf_password.setPreferredSize(new java.awt.Dimension(300, 40));
        pf_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pf_passwordMouseClicked(evt);
            }
        });
        pf_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pf_passwordKeyReleased(evt);
            }
        });
        jPanel3.add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 300, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/vt.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 420));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        setSize(new java.awt.Dimension(400, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //check_userlogin();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        int isOK = JOptionPane.showConfirmDialog(this, "Are you sure?", "Conform!", JOptionPane.YES_NO_OPTION, JOptionPane.CLOSED_OPTION);
        if (isOK == JOptionPane.YES_OPTION) {

            System.exit(0);

        }

    }//GEN-LAST:event_jLabel6MouseClicked

    private void tf_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_usernameMouseClicked

        tf_username.setBackground(Color.WHITE);

    }//GEN-LAST:event_tf_usernameMouseClicked

    private void pf_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_passwordMouseClicked

        pf_password.setBackground(Color.WHITE);

    }//GEN-LAST:event_pf_passwordMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        JOptionPane.showMessageDialog(this, "Contact Administrator!");

    }//GEN-LAST:event_jLabel4MouseClicked
    int i = 0;
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        i++;
        if (i >= 3) {
            //JOptionPane.showMessageDialog(this, "System Has Thread! \n Automatically System Shoutdown");
            int y = JOptionPane.showConfirmDialog(this, "System Shoutdown", "WARNING!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (y == JOptionPane.YES_OPTION) {
                System.exit(0);
            } else {
                i = 0;
                tf_username.setText("");
                pf_password.setText("");
            }

        } else {
            String username = tf_username.getText().trim().toLowerCase();
            String password = new String(pf_password.getPassword()).trim();

            if (!(username == "" && password == "")) {
                check_userlogin(username, password);

            } else {
                if ("".equals(username)) {
                    tf_username.setBackground(Color.yellow);
                } else if ("".equals(password)) {
                    pf_password.setBackground(Color.yellow);
                }

            }
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void pf_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_passwordKeyReleased

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {

            if (i >= 3) {
                //JOptionPane.showMessageDialog(this, "System Has Thread! \n Automatically System Shoutdown");
                int y = JOptionPane.showConfirmDialog(this, "System Shoutdown", "WARNING!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (y == JOptionPane.YES_OPTION) {
                    System.exit(0);
                } else {
                    i = 0;
                    tf_username.setText("");
                    pf_password.setText("");
                }

            } else {

                String username = tf_username.getText().trim().toLowerCase();
                String password = new String(pf_password.getPassword()).trim();

                if (!(username.isEmpty() && password.isEmpty())) {
                    check_userlogin(username, password);

                } else {
                    if (username.isEmpty()) {
                        tf_username.setBackground(Color.yellow);
                    } else if (password.isEmpty()) {
                        pf_password.setBackground(Color.yellow);
                    }

                }
            }
            i++;
        }

    }//GEN-LAST:event_pf_passwordKeyReleased

    private void tf_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_usernameKeyReleased

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            pf_password.grabFocus();
        }

    }//GEN-LAST:event_tf_usernameKeyReleased

    int gotoAdmin=0;
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        gotoAdmin++;
        if (gotoAdmin==10) {
            this.dispose();
            new Admin_workArea(10).setVisible(true);
        }
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseMoved

        //jLabel8.setToolTipText("Safe Area");
        //JOptionPane.showMessageDialog(this, "Safe Mode ON");
        
    }//GEN-LAST:event_jLabel8MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            user_login uu=new user_login();
            //uu.setIconImage(CreateImagesss("/FormatFactoryicon100.png").getImage());
            uu.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_locklogin;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables

    private void check_userlogin(String username, String password) {

        if (username != "" && password != "") {

            try {

                ResultSet rs_username;
                ResultSet rs_password;

                rs_username = MC_DB.search_dataOne("user_account", "us_username", username);
                rs_password = MC_DB.search_dataOne("user_account", "us_password", password);

                if (rs_username.next()) {
                    if (rs_password.next()) {

                        // JOptionPane.showMessageDialog(this, "user status" + rs_username.getInt("us_status"));
                        if (rs_username.getInt("us_status") == 00) {
                            JOptionPane.showMessageDialog(this, "Your Are Not System Access!");
                        } else {
                            Check_login_type(rs_username.getInt("us_status"));
                            //login success
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid Password!\n Please try again!");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Username!\n Please try again!");
                }
            } catch (HeadlessException | SQLException e) {
                e.printStackTrace();
            }

        }
        //ResultSet search_username = MC_JavaDataBaseConnection.search_data("user_account", "us_username", username);
        //ResultSet search_password = MC_JavaDataBaseConnection.search_data("user_account", "us_password", password);
        //String type = search_username.getString("us_type");
        //int iftype = login_check(type);
        // System.out.println("Return :"+iftype);
    }

    private void Check_login_type(int a_type) {

        //ResultSet check_status = MC_JavaDataBaseConnection.search_dataOne("user_account", a_type + "", user_type);
        if (a_type == 11) {

            JOptionPane.showMessageDialog(this, "Admin is Successfully Login! ");
            this.dispose();
            Admin_workArea admin = new Admin_workArea();
            admin.setVisible(true);
//                            JOptionPane.showMessageDialog(this, "User is Login! ");
        } else if (a_type == 10) {

            JOptionPane.showMessageDialog(this, "User Is Not a Active Admin! \n Contact Administrator! ");
        } else if (a_type == 01) {
            JOptionPane.showMessageDialog(this, "User is Successfully Login! ");
            this.dispose();
            Admin_workArea user = new Admin_workArea();
            user.setVisible(true);
        } else if (a_type == 00) {
            JOptionPane.showMessageDialog(this, "User Is Not a Active User! \n Contact Administrator ");
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
        }

    }
    
    public static ImageIcon CreateImagesss(String path){
        //setIconImage(CreateImagesss("/FormatFactoryicon100.png").getImage());
        return new ImageIcon(java.awt.Toolkit.getDefaultToolkit().getClass().getResource(path));
    
    }

}
