package com.softidea.www.private_access.adminstrator;

import com.fsczone.www.lookAndFeel.pro_lookandfeel;
import com.softidea.www.public_access.login_user.user_login;
import com.softidea.www.public_connection.MC_DB;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;

public class Admin_workArea extends javax.swing.JFrame {

    public String usermail_display;

    public Admin_workArea() {
        //this.setIconImage(CreateImagesss("/FormatFactoryicon100.png").getImage());

        initComponents();
        new Thread(() -> {
            try {

                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
                }
                showDate();
                showTime();
                md_HomeMenuVisibleLabel(false);

                try {
                    AWTUtilities.setWindowOpaque(this, false);
                } catch (Exception e) {
                }
                pro_lookandfeel.Set();

                loadCusFundCount();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    }

    public Admin_workArea(int i) {
        //this.setIconImage(CreateImagesss("/FormatFactoryicon100.png").getImage());
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
        }
        md_HomeMenuVisibleLabel(false);
        try {
            AWTUtilities.setWindowOpaque(this, false);
        } catch (Exception e) {
        }
        pro_lookandfeel.Set();

        if (i == 10) {
            bt_administratormang.setEnabled(true);
            bt_cashmang.setEnabled(false);
            bt_cusmang.setEnabled(false);
            bt_installmentmang1.setEnabled(false);
            bt_fungmang.setEnabled(false);
            bt_installmentmang.setEnabled(false);
            bt_loanmang.setEnabled(false);
            bt_reports.setEnabled(false);
            bt_usermang.setEnabled(true);
        }
        loadCusFundCount();

    }

    public Admin_workArea(String userMail) {

        initComponents();

        try {

            if(userMail.equals("User")){
                bt_loanmang.setVisible(false);
                bt_cashmang.setVisible(false);
                bt_usermang.setVisible(false);
                bt_administratormang.setVisible(false);
                bt_reports.setVisible(false);
            }
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_OmainMenu = new javax.swing.JPanel();
        bt_Ouser = new javax.swing.JButton();
        bt_Ocustomer = new javax.swing.JButton();
        bt_Ofund = new javax.swing.JButton();
        bt_Oinstallment = new javax.swing.JButton();
        bt_Ocash = new javax.swing.JButton();
        bt_Oloan = new javax.swing.JButton();
        bt_Oadministrator = new javax.swing.JButton();
        bt_Oreports = new javax.swing.JButton();
        bt_customerexesits = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lb_customerCount3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lb_v_date = new javax.swing.JLabel();
        lb_funderCount3 = new javax.swing.JLabel();
        lb_v_time = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pl_systemExit = new javax.swing.JPanel();
        jl_systemExit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_wk_option1 = new javax.swing.JLabel();
        lb_wk_option2 = new javax.swing.JLabel();
        lb_wk_option3 = new javax.swing.JLabel();
        lb_wk_option4 = new javax.swing.JLabel();
        lb_wk_option5 = new javax.swing.JLabel();
        lb_wk_option6 = new javax.swing.JLabel();
        lb_wk_option8 = new javax.swing.JLabel();
        lb_wk_option7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jp_adminMainPanel = new javax.swing.JPanel();
        bt_usermang = new javax.swing.JButton();
        bt_cusmang = new javax.swing.JButton();
        bt_fungmang = new javax.swing.JButton();
        bt_installmentmang = new javax.swing.JButton();
        bt_cashmang = new javax.swing.JButton();
        bt_loanmang = new javax.swing.JButton();
        bt_administratormang = new javax.swing.JButton();
        bt_reports = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lb_customerCount = new javax.swing.JLabel();
        lb_time = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        lb_funderCount = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bt_installmentmang1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jp_OmainMenu.setBackground(new java.awt.Color(102, 102, 102));
        jp_OmainMenu.setMaximumSize(new java.awt.Dimension(1300, 600));
        jp_OmainMenu.setMinimumSize(new java.awt.Dimension(1300, 600));
        jp_OmainMenu.setPreferredSize(new java.awt.Dimension(1300, 600));
        jp_OmainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_Ouser.setBackground(new java.awt.Color(0, 153, 102));
        bt_Ouser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Ouser.setForeground(new java.awt.Color(255, 255, 255));
        bt_Ouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_user.png"))); // NOI18N
        bt_Ouser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Ouser.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Ouser.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Ouser.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_user.png"))); // NOI18N
        bt_Ouser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OuserActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Ouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 200, 200));

        bt_Ocustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Ocustomer.setForeground(new java.awt.Color(255, 255, 255));
        bt_Ocustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_customer.png"))); // NOI18N
        bt_Ocustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Ocustomer.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Ocustomer.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Ocustomer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_customer.png"))); // NOI18N
        bt_Ocustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OcustomerActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Ocustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 115, 200, 200));

        bt_Ofund.setBackground(new java.awt.Color(0, 153, 102));
        bt_Ofund.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Ofund.setForeground(new java.awt.Color(255, 255, 255));
        bt_Ofund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_fund.png"))); // NOI18N
        bt_Ofund.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Ofund.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Ofund.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Ofund.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_fund.png"))); // NOI18N
        bt_Ofund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OfundActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Ofund, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 200, 200));

        bt_Oinstallment.setBackground(new java.awt.Color(0, 153, 102));
        bt_Oinstallment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Oinstallment.setForeground(new java.awt.Color(255, 255, 255));
        bt_Oinstallment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_installment.png"))); // NOI18N
        bt_Oinstallment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Oinstallment.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Oinstallment.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Oinstallment.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_installment.png"))); // NOI18N
        bt_Oinstallment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OinstallmentActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Oinstallment, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 200, 200));

        bt_Ocash.setBackground(new java.awt.Color(0, 153, 102));
        bt_Ocash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Ocash.setForeground(new java.awt.Color(255, 255, 255));
        bt_Ocash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_cash.png"))); // NOI18N
        bt_Ocash.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Ocash.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Ocash.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Ocash.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_cash.png"))); // NOI18N
        bt_Ocash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OcashActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Ocash, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 333, 200, 200));

        bt_Oloan.setBackground(new java.awt.Color(0, 153, 102));
        bt_Oloan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Oloan.setForeground(new java.awt.Color(255, 255, 255));
        bt_Oloan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_loan.png"))); // NOI18N
        bt_Oloan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Oloan.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Oloan.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Oloan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_loan.png"))); // NOI18N
        bt_Oloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OloanActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Oloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 200, 200));

        bt_Oadministrator.setBackground(new java.awt.Color(0, 153, 102));
        bt_Oadministrator.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Oadministrator.setForeground(new java.awt.Color(255, 255, 255));
        bt_Oadministrator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_administrator.png"))); // NOI18N
        bt_Oadministrator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Oadministrator.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Oadministrator.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Oadministrator.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        bt_Oadministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OadministratorActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Oadministrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 333, 200, 200));

        bt_Oreports.setBackground(new java.awt.Color(0, 153, 102));
        bt_Oreports.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Oreports.setForeground(new java.awt.Color(255, 255, 255));
        bt_Oreports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_reports.png"))); // NOI18N
        bt_Oreports.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Oreports.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Oreports.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Oreports.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_reports.png"))); // NOI18N
        bt_Oreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OreportsActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Oreports, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 333, 200, 200));

        bt_customerexesits.setBackground(new java.awt.Color(0, 153, 102));
        bt_customerexesits.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_customerexesits.setForeground(new java.awt.Color(255, 255, 255));
        bt_customerexesits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_customerExitsManagement.png"))); // NOI18N
        bt_customerexesits.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_customerexesits.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_customerexesits.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_customerexesits.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_customerExitsManagement.png"))); // NOI18N
        bt_customerexesits.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_customerexesitsMouseMoved(evt);
            }
        });
        bt_customerexesits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_customerexesitsActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_customerexesits, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, 200, 200));

        jPanel5.setBackground(new java.awt.Color(0, 200, 83));
        jPanel5.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel5.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel5MouseMoved(evt);
            }
        });

        lb_customerCount3.setBackground(new java.awt.Color(255, 255, 255));
        lb_customerCount3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_customerCount3.setForeground(new java.awt.Color(255, 255, 255));
        lb_customerCount3.setText("CCT");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Time");

        lb_v_date.setBackground(new java.awt.Color(255, 255, 255));
        lb_v_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_v_date.setForeground(new java.awt.Color(255, 255, 255));
        lb_v_date.setText("Date");

        lb_funderCount3.setBackground(new java.awt.Color(255, 255, 255));
        lb_funderCount3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_funderCount3.setForeground(new java.awt.Color(255, 255, 255));
        lb_funderCount3.setText("FCT");

        lb_v_time.setBackground(new java.awt.Color(255, 255, 255));
        lb_v_time.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_v_time.setForeground(new java.awt.Color(255, 255, 255));
        lb_v_time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_v_time.setText("CCT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_v_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lb_customerCount3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_funderCount3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_v_time, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_customerCount3)
                    .addComponent(lb_funderCount3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_v_time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_v_date, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jp_OmainMenu.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 333, -1, 200));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/Vector-PNG-Pictureright.png"))); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jp_OmainMenu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/vt.png"))); // NOI18N
        jp_OmainMenu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 94, 390, 510));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pl_systemExit.setBackground(new java.awt.Color(33, 33, 33));
        pl_systemExit.setLayout(new java.awt.CardLayout());

        jl_systemExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_systemExit.setForeground(new java.awt.Color(255, 255, 255));
        jl_systemExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_systemExit.setText("X");
        jl_systemExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jl_systemExitMouseMoved(evt);
            }
        });
        jl_systemExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_systemExitMouseClicked(evt);
            }
        });
        pl_systemExit.add(jl_systemExit, "card2");

        getContentPane().add(pl_systemExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1275, 23, 25, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Softidea Solution (Pvt) Ltd.");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1054, 680, 200, -1));

        lb_wk_option1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option1.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option1.setText("Home");
        lb_wk_option1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_option1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_option1MouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 145, 35));

        lb_wk_option2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option2.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option2.setText("Customer");
        lb_wk_option2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_option2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_option2MouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 145, 35));

        lb_wk_option3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option3.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option3.setText("Fund");
        lb_wk_option3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_option3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_option3MouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 145, 35));

        lb_wk_option4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option4.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option4.setText("Installment");
        lb_wk_option4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_option4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 145, 35));

        lb_wk_option5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option5.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option5.setText("Cash Account");
        lb_wk_option5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_option5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 145, 35));

        lb_wk_option6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option6.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option6.setText("Pendding Customer");
        lb_wk_option6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_option6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 145, 35));

        lb_wk_option8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option8.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option8.setText("My Account");
        lb_wk_option8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_option8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_option8MouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_option8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 145, 35));

        lb_wk_option7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option7.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option7.setText("Close Customer");
        lb_wk_option7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_option7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 145, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Administrator | Work Area");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/private_access/images/frame_admin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        jp_adminMainPanel.setBackground(new java.awt.Color(102, 102, 102));
        jp_adminMainPanel.setFocusCycleRoot(true);
        jp_adminMainPanel.setPreferredSize(new java.awt.Dimension(1300, 400));
        jp_adminMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_usermang.setBackground(new java.awt.Color(0, 153, 102));
        bt_usermang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_usermang.setForeground(new java.awt.Color(255, 255, 255));
        bt_usermang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_user.png"))); // NOI18N
        bt_usermang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_usermang.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_usermang.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_usermang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_usermangMouseMoved(evt);
            }
        });
        bt_usermang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_usermangActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(bt_usermang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 200, 200));

        bt_cusmang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_cusmang.setForeground(new java.awt.Color(255, 255, 255));
        bt_cusmang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_customer.png"))); // NOI18N
        bt_cusmang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cusmang.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_cusmang.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_cusmang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_cusmangMouseMoved(evt);
            }
        });
        bt_cusmang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cusmangActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(bt_cusmang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 200, 200));

        bt_fungmang.setBackground(new java.awt.Color(0, 153, 102));
        bt_fungmang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_fungmang.setForeground(new java.awt.Color(255, 255, 255));
        bt_fungmang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_fund.png"))); // NOI18N
        bt_fungmang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_fungmang.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_fungmang.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_fungmang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_fungmangMouseMoved(evt);
            }
        });
        bt_fungmang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fungmangActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(bt_fungmang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 200, 200));

        bt_installmentmang.setBackground(new java.awt.Color(0, 153, 102));
        bt_installmentmang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_installmentmang.setForeground(new java.awt.Color(255, 255, 255));
        bt_installmentmang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_customerExitsManagement.png"))); // NOI18N
        bt_installmentmang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_installmentmang.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_installmentmang.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_installmentmang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_installmentmangMouseMoved(evt);
            }
        });
        bt_installmentmang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_installmentmangActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(bt_installmentmang, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 115, 200, 200));

        bt_cashmang.setBackground(new java.awt.Color(0, 153, 102));
        bt_cashmang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_cashmang.setForeground(new java.awt.Color(255, 255, 255));
        bt_cashmang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_cash.png"))); // NOI18N
        bt_cashmang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cashmang.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_cashmang.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_cashmang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cashmangActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(bt_cashmang, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 333, 200, 200));

        bt_loanmang.setBackground(new java.awt.Color(0, 153, 102));
        bt_loanmang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_loanmang.setForeground(new java.awt.Color(255, 255, 255));
        bt_loanmang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_loan.png"))); // NOI18N
        bt_loanmang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_loanmang.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_loanmang.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_loanmang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loanmangActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(bt_loanmang, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 200, 200));

        bt_administratormang.setBackground(new java.awt.Color(0, 153, 102));
        bt_administratormang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_administratormang.setForeground(new java.awt.Color(255, 255, 255));
        bt_administratormang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_administrator.png"))); // NOI18N
        bt_administratormang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_administratormang.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_administratormang.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_administratormang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administratormangActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(bt_administratormang, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 333, 200, 200));

        bt_reports.setBackground(new java.awt.Color(0, 153, 102));
        bt_reports.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_reports.setForeground(new java.awt.Color(255, 255, 255));
        bt_reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_reports.png"))); // NOI18N
        bt_reports.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_reports.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_reports.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reportsActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(bt_reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 333, 200, 200));

        jPanel1.setBackground(new java.awt.Color(0, 200, 83));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));

        lb_customerCount.setBackground(new java.awt.Color(255, 255, 255));
        lb_customerCount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_customerCount.setForeground(new java.awt.Color(255, 255, 255));
        lb_customerCount.setText("CCT");

        lb_time.setBackground(new java.awt.Color(255, 255, 255));
        lb_time.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        lb_time.setForeground(new java.awt.Color(255, 255, 255));
        lb_time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_time.setText("00:00:00");

        lb_date.setBackground(new java.awt.Color(255, 255, 255));
        lb_date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_date.setForeground(new java.awt.Color(255, 255, 255));
        lb_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_date.setText("2016-08-14");

        lb_funderCount.setBackground(new java.awt.Color(255, 255, 255));
        lb_funderCount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_funderCount.setForeground(new java.awt.Color(255, 255, 255));
        lb_funderCount.setText("FCT");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Customer Count");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Funder Count");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lb_customerCount, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_funderCount, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_customerCount)
                    .addComponent(lb_funderCount))
                .addGap(4, 4, 4)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jp_adminMainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 333, 210, 200));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/Vector-PNG-Pictureright.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jp_adminMainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/vt.png"))); // NOI18N
        jp_adminMainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 94, 390, 510));

        bt_installmentmang1.setBackground(new java.awt.Color(0, 153, 102));
        bt_installmentmang1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bt_installmentmang1.setForeground(new java.awt.Color(255, 255, 255));
        bt_installmentmang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/btn_installment.png"))); // NOI18N
        bt_installmentmang1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_installmentmang1.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_installmentmang1.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_installmentmang1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_installmentmang1MouseMoved(evt);
            }
        });
        bt_installmentmang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_installmentmang1ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(bt_installmentmang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 200, 200));

        getContentPane().add(jp_adminMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1300, 600));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/private_access/images/under_frame.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1300, 30));

        setSize(new java.awt.Dimension(1300, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Border borderC = BorderFactory.createLineBorder(new Color(255, 255, 255), 1);
    private void jl_systemExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_systemExitMouseMoved

        pl_systemExit.setBorder(borderC);

    }//GEN-LAST:event_jl_systemExitMouseMoved

    private void jl_systemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_systemExitMouseClicked

        //System.exit(0);
        this.dispose();
        user_login uslg = new user_login();
        uslg.setVisible(true);

    }//GEN-LAST:event_jl_systemExitMouseClicked

    private void lb_wk_option2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_option2MouseClicked

        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_customer_managment();
        }).start();
        lb_wk_option2.setVisible(false);

    }//GEN-LAST:event_lb_wk_option2MouseClicked

    private void lb_wk_option8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_option8MouseClicked

//        try {
//            jp_adminMainPanel.removeAll();
//            jp_adminMainPanel.setLayout(new FlowLayout());
//            Admin_customerSettings settings = new Admin_customerSettings();
//            settings.setVisible(true);
//            jp_adminMainPanel.add(settings);
//            jp_adminMainPanel.updateUI();
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }

    }//GEN-LAST:event_lb_wk_option8MouseClicked

    private void lb_wk_option3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_option3MouseClicked


    }//GEN-LAST:event_lb_wk_option3MouseClicked

    private void bt_usermangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_usermangActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_user_managment();
        }).start();

    }//GEN-LAST:event_bt_usermangActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().browse(new URI("http://www.fsczone.com/"));
            }
        } catch (URISyntaxException | IOException e) {
        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void lb_wk_option1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_option1MouseClicked

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        showDate();
        showTime();
        md_HomeMenuVisibleLabel(false);
        try {
            AWTUtilities.setWindowOpaque(this, false);
        } catch (Exception e) {
        }
        pro_lookandfeel.Set();

        loadCusFundCount();

        lb_wk_option1.setVisible(false);
        lb_wk_option2.setVisible(false);

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            jp_OmainMenu.setVisible(true);
            jp_adminMainPanel.add(jp_OmainMenu);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_lb_wk_option1MouseClicked

    private void bt_cusmangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cusmangActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_customer_managment();
        }).start();


    }//GEN-LAST:event_bt_cusmangActionPerformed

    private void bt_fungmangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fungmangActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);

//            lb_wk_option1.setText("Hello");
//            lb_wk_option1.addMouseListener(new MouseListener() {
//
//                @Override
//                public void mouseClicked(MouseEvent me) {
//
//                    lb_wk_option2.setVisible(true);
//
//                }
//
//                @Override
//                public void mousePressed(MouseEvent me) {
//
//                }
//
//                @Override
//                public void mouseReleased(MouseEvent me) {
//
//                }
//
//                @Override
//                public void mouseEntered(MouseEvent me) {
//
//                }
//
//                @Override
//                public void mouseExited(MouseEvent me) {
//
//                }
//            });
            load_fundManagment();
        }).start();

    }//GEN-LAST:event_bt_fungmangActionPerformed

    private void bt_installmentmangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_installmentmangActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_Addditonal_Loans();
        }).start();


    }//GEN-LAST:event_bt_installmentmangActionPerformed

    private void bt_cashmangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cashmangActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_cashManagment();
        }).start();


    }//GEN-LAST:event_bt_cashmangActionPerformed

    private void bt_loanmangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loanmangActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_loanManagment();
        }).start();


    }//GEN-LAST:event_bt_loanmangActionPerformed

    private void bt_administratormangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administratormangActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_admin_managment();
        }).start();


    }//GEN-LAST:event_bt_administratormangActionPerformed

    private void bt_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reportsActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_reportManagment();
        }).start();


    }//GEN-LAST:event_bt_reportsActionPerformed

    private void bt_OuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OuserActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_user_managment();
        }).start();

    }//GEN-LAST:event_bt_OuserActionPerformed

    private void bt_OcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OcustomerActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_customer_managment();
        }).start();

    }//GEN-LAST:event_bt_OcustomerActionPerformed

    private void bt_OfundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OfundActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_fundManagment();
        }).start();

    }//GEN-LAST:event_bt_OfundActionPerformed

    private void bt_OinstallmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OinstallmentActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_installmentManagment();
        }).start();

    }//GEN-LAST:event_bt_OinstallmentActionPerformed

    private void bt_OcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OcashActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_cashManagment();
        }).start();

    }//GEN-LAST:event_bt_OcashActionPerformed

    private void bt_OloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OloanActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_loanManagment();
        }).start();

    }//GEN-LAST:event_bt_OloanActionPerformed

    private void bt_OadministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OadministratorActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_admin_managment();
        }).start();

    }//GEN-LAST:event_bt_OadministratorActionPerformed

    private void bt_OreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OreportsActionPerformed
        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_reportManagment();
        }).start();

    }//GEN-LAST:event_bt_OreportsActionPerformed

    private void bt_usermangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_usermangMouseMoved

        bt_usermang.setBorder(borderC);

    }//GEN-LAST:event_bt_usermangMouseMoved

    private void bt_cusmangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cusmangMouseMoved

        bt_cusmang.setBorder(borderC);

    }//GEN-LAST:event_bt_cusmangMouseMoved

    private void bt_fungmangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_fungmangMouseMoved

        bt_fungmang.setBorder(borderC);

    }//GEN-LAST:event_bt_fungmangMouseMoved

    private void bt_installmentmangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_installmentmangMouseMoved


    }//GEN-LAST:event_bt_installmentmangMouseMoved

    private void bt_installmentmang1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_installmentmang1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_installmentmang1MouseMoved

    private void bt_installmentmang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_installmentmang1ActionPerformed

        new Thread(() -> {
            lb_wk_option1.setVisible(true);
            load_installmentManagment();
        }).start();


    }//GEN-LAST:event_bt_installmentmang1ActionPerformed

    private void bt_customerexesitsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_customerexesitsMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_customerexesitsMouseMoved

    private void bt_customerexesitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_customerexesitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_customerexesitsActionPerformed

    private void jPanel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseMoved

        showDate();
        showTime();


    }//GEN-LAST:event_jPanel5MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Admin_workArea aa = new Admin_workArea();
            aa.setIconImage(CreateImagesss("/FormatFactoryicon100.png").getImage());
            aa.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Oadministrator;
    private javax.swing.JButton bt_Ocash;
    private javax.swing.JButton bt_Ocustomer;
    private javax.swing.JButton bt_Ofund;
    private javax.swing.JButton bt_Oinstallment;
    private javax.swing.JButton bt_Oloan;
    private javax.swing.JButton bt_Oreports;
    private javax.swing.JButton bt_Ouser;
    private javax.swing.JButton bt_administratormang;
    private javax.swing.JButton bt_cashmang;
    private javax.swing.JButton bt_cusmang;
    private javax.swing.JButton bt_customerexesits;
    private javax.swing.JButton bt_fungmang;
    private javax.swing.JButton bt_installmentmang;
    private javax.swing.JButton bt_installmentmang1;
    private javax.swing.JButton bt_loanmang;
    private javax.swing.JButton bt_reports;
    private javax.swing.JButton bt_usermang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jl_systemExit;
    public javax.swing.JPanel jp_OmainMenu;
    public static javax.swing.JPanel jp_adminMainPanel;
    private javax.swing.JLabel lb_customerCount;
    private javax.swing.JLabel lb_customerCount3;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_funderCount;
    private javax.swing.JLabel lb_funderCount3;
    private javax.swing.JLabel lb_time;
    private javax.swing.JLabel lb_v_date;
    private javax.swing.JLabel lb_v_time;
    public static javax.swing.JLabel lb_wk_option1;
    public static javax.swing.JLabel lb_wk_option2;
    public static javax.swing.JLabel lb_wk_option3;
    public static javax.swing.JLabel lb_wk_option4;
    public static javax.swing.JLabel lb_wk_option5;
    public static javax.swing.JLabel lb_wk_option6;
    public static javax.swing.JLabel lb_wk_option7;
    public static javax.swing.JLabel lb_wk_option8;
    private javax.swing.JPanel pl_systemExit;
    // End of variables declaration//GEN-END:variables

    private void load_user_managment() {

        new Thread(() -> {
            try {
                jp_adminMainPanel.removeAll();
                jp_adminMainPanel.setLayout(new FlowLayout());
                Admin_userManagment user = new Admin_userManagment();
                user.setVisible(true);
                jp_adminMainPanel.add(user);
                jp_adminMainPanel.updateUI();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    }

    private void load_fundManagment() {

        new Thread(() -> {
            try {
                jp_adminMainPanel.removeAll();
                jp_adminMainPanel.setLayout(new FlowLayout());
                Admin_fundManagment ai = new Admin_fundManagment();
                ai.setVisible(true);
                jp_adminMainPanel.add(ai);
                jp_adminMainPanel.updateUI();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    }

    private void load_installmentManagment() {

        new Thread(() -> {
            try {
                jp_adminMainPanel.removeAll();
                jp_adminMainPanel.setLayout(new FlowLayout());
                Admin_installmentManagment am = new Admin_installmentManagment();
                am.setVisible(true);
                jp_adminMainPanel.add(am);
                jp_adminMainPanel.updateUI();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    }

    private void load_Addditonal_Loans() {

        new Thread(() -> {
            try {
                jp_adminMainPanel.removeAll();
                jp_adminMainPanel.setLayout(new FlowLayout());
                Admin_customerExitsManagement am = new Admin_customerExitsManagement();
                am.setVisible(true);
                jp_adminMainPanel.add(am);
                jp_adminMainPanel.updateUI();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    }

    private void loadCusFundCount() {
        new Thread(() -> {
            try {
                ResultSet rs = MC_DB.myConnection().createStatement().executeQuery("SELECT COUNT(DISTINCT idcustomer) AS NumberOfCustomers FROM customer;");
                //ResultSet r2=MC_DB.myConnection().createStatement().executeQuery("SELECT COUNT(DISTINCT idfunder) AS NumberOfFunders FROM funder;");
                if (rs.next()) {
                    String cusCount = rs.getString("NumberOfCustomers");
                    lb_customerCount.setText(cusCount);

                }

                ResultSet r2 = MC_DB.myConnection().createStatement().executeQuery("SELECT COUNT(DISTINCT idfunder) AS NumberOfFunders FROM funder;");

                if (r2.next()) {
                    String funderCount = r2.getString("NumberOfFunders");
                    lb_funderCount.setText(funderCount);
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }).start();

    }

    private void load_admin_managment() {
        new Thread(() -> {
            try {
                jp_adminMainPanel.removeAll();
                jp_adminMainPanel.setLayout(new FlowLayout());
                Admin_adminManagment aiq = new Admin_adminManagment();
                aiq.setVisible(true);
                jp_adminMainPanel.add(aiq);
                jp_adminMainPanel.updateUI();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    }

    private void load_customer_managment() {
        new Thread(() -> {
            try {
                jp_adminMainPanel.removeAll();
                jp_adminMainPanel.setLayout(new FlowLayout());
                Admin_customerManagment cus_add = new Admin_customerManagment();
                cus_add.setVisible(true);
                jp_adminMainPanel.add(cus_add);
                jp_adminMainPanel.updateUI();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    }

    private void md_HomeMenuVisibleLabel(boolean visible) {

        lb_wk_option1.setVisible(visible);
        lb_wk_option2.setVisible(visible);
        lb_wk_option3.setVisible(visible);
        lb_wk_option4.setVisible(visible);
        lb_wk_option5.setVisible(visible);
        lb_wk_option6.setVisible(visible);
        lb_wk_option7.setVisible(visible);
        lb_wk_option8.setVisible(visible);

    }

    private void load_cashManagment() {

        new Thread(() -> {
            try {
                jp_adminMainPanel.removeAll();
                jp_adminMainPanel.setLayout(new FlowLayout());
                Admin_cashManagment am = new Admin_cashManagment();
                am.setVisible(true);
                jp_adminMainPanel.add(am);
                jp_adminMainPanel.updateUI();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    }

    private void load_loanManagment() {

        new Thread(() -> {
            try {
                jp_adminMainPanel.removeAll();
                jp_adminMainPanel.setLayout(new FlowLayout());
                Admin_loanManagment am = new Admin_loanManagment();
                am.setVisible(true);
                jp_adminMainPanel.add(am);
                jp_adminMainPanel.updateUI();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    }

    private void load_reportManagment() {

        new Thread(() -> {
            try {
                jp_adminMainPanel.removeAll();
                jp_adminMainPanel.setLayout(new FlowLayout());
                Admin_reportManagment am = new Admin_reportManagment();
                am.setVisible(true);
                jp_adminMainPanel.add(am);
                jp_adminMainPanel.updateUI();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

    }

    ///////////// load date and time
    final void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {

                Date d = new Date();
                SimpleDateFormat stim = new SimpleDateFormat("hh:mm:ss a");
                String st = stim.format(d);
                lb_time.setText(st);

            }
        }).start();
    }

    final void showTime2() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {

                Date d = new Date();
                SimpleDateFormat stim = new SimpleDateFormat("hh:mm:ss a");
                String st = stim.format(d);
                lb_v_time.setText(st);

            }
        }).start();
    }

    final void showDate() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String s = sdf.format(d);
        lb_date.setText(s);
        System.out.println(s);

    }

    final void showDate2() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String s = sdf.format(d);
        lb_v_date.setText(s);
        System.out.println(s);

    }

    public static ImageIcon CreateImagesss(String path) {
        //setIconImage(CreateImagesss("/FormatFactoryicon100.png").getImage());
        return new ImageIcon(java.awt.Toolkit.getDefaultToolkit().getClass().getResource(path));

    }

}
