/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softidea.www.private_access.adminstrator;

import com.fsczone.www.lookAndFeel.pro_lookandfeel;
import com.softidea.www.public_access.login_user.user_login;
import com.softidea.www.public_connection.MC_DB;
import com.sun.awt.AWTUtilities;
import java.awt.Desktop;
import java.awt.FlowLayout;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author deepalsuranga
 */
public class Admin_workArea extends javax.swing.JFrame {

    /**
     * Creates new form admin_index
     */
    public Admin_workArea() {
        initComponents();
        md_HomeMenuVisibleLabel(false);
        try {
            AWTUtilities.setWindowOpaque(this, false);
        } catch (Exception e) {
        }
        pro_lookandfeel.Set();

        loadCusFundCount();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_OmainMenu = new javax.swing.JPanel();
        bt_Ouser = new javax.swing.JButton();
        bt_Ocustomer = new javax.swing.JButton();
        bt_Ofund = new javax.swing.JButton();
        bt_Oinstallment = new javax.swing.JButton();
        bt_Ocash = new javax.swing.JButton();
        bt_Oloan = new javax.swing.JButton();
        bt_Oadministrator = new javax.swing.JButton();
        bt_Oreports = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lb_customerCount2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_funderCount2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lb_customerCount3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lb_funderCount3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pl_systemExit = new javax.swing.JPanel();
        jl_systemExit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_wk_option1 = new javax.swing.JLabel();
        lb_wk_option2 = new javax.swing.JLabel();
        lb_wk_option3 = new javax.swing.JLabel();
        lb_wk_option4 = new javax.swing.JLabel();
        lb_wk_option5 = new javax.swing.JLabel();
        lb_wk_option6 = new javax.swing.JLabel();
        lb_wk_option8 = new javax.swing.JLabel();
        lb_wk_option7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jp_adminMainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb_customerCount1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_funderCount1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_customerCount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_funderCount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jp_OmainMenu.setBackground(new java.awt.Color(102, 102, 102));
        jp_OmainMenu.setMaximumSize(new java.awt.Dimension(1300, 600));
        jp_OmainMenu.setMinimumSize(new java.awt.Dimension(1300, 600));
        jp_OmainMenu.setPreferredSize(new java.awt.Dimension(1300, 600));
        jp_OmainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_Ouser.setBackground(new java.awt.Color(0, 153, 102));
        bt_Ouser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Ouser.setForeground(new java.awt.Color(255, 255, 255));
        bt_Ouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        bt_Ouser.setText("User Managment");
        bt_Ouser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Ouser.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Ouser.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Ouser.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        bt_Ouser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OuserActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Ouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 115, 200, 200));

        bt_Ocustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Ocustomer.setForeground(new java.awt.Color(255, 255, 255));
        bt_Ocustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        bt_Ocustomer.setText("Customer Managment");
        bt_Ocustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Ocustomer.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Ocustomer.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Ocustomer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        bt_Ocustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OcustomerActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Ocustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 115, 200, 200));

        bt_Ofund.setBackground(new java.awt.Color(0, 153, 102));
        bt_Ofund.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Ofund.setForeground(new java.awt.Color(255, 255, 255));
        bt_Ofund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        bt_Ofund.setText("Fund Managment");
        bt_Ofund.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Ofund.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Ofund.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Ofund.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        bt_Ofund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OfundActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Ofund, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 115, 200, 200));

        bt_Oinstallment.setBackground(new java.awt.Color(0, 153, 102));
        bt_Oinstallment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Oinstallment.setForeground(new java.awt.Color(255, 255, 255));
        bt_Oinstallment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        bt_Oinstallment.setText("Installment Management");
        bt_Oinstallment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Oinstallment.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Oinstallment.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Oinstallment.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        bt_Oinstallment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OinstallmentActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Oinstallment, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 115, 200, 200));

        bt_Ocash.setBackground(new java.awt.Color(0, 153, 102));
        bt_Ocash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Ocash.setForeground(new java.awt.Color(255, 255, 255));
        bt_Ocash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        bt_Ocash.setText("Cash Management");
        bt_Ocash.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Ocash.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Ocash.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Ocash.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        bt_Ocash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OcashActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Ocash, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 333, 200, 200));

        bt_Oloan.setBackground(new java.awt.Color(0, 153, 102));
        bt_Oloan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Oloan.setForeground(new java.awt.Color(255, 255, 255));
        bt_Oloan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        bt_Oloan.setText("Loan Managment");
        bt_Oloan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Oloan.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Oloan.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Oloan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        bt_Oloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OloanActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Oloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 333, 200, 200));

        bt_Oadministrator.setBackground(new java.awt.Color(0, 153, 102));
        bt_Oadministrator.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Oadministrator.setForeground(new java.awt.Color(255, 255, 255));
        bt_Oadministrator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        bt_Oadministrator.setText("Administrator Managment");
        bt_Oadministrator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Oadministrator.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Oadministrator.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Oadministrator.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        bt_Oadministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OadministratorActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Oadministrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 333, 200, 200));

        bt_Oreports.setBackground(new java.awt.Color(0, 153, 102));
        bt_Oreports.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_Oreports.setForeground(new java.awt.Color(255, 255, 255));
        bt_Oreports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        bt_Oreports.setText("Reports Managment");
        bt_Oreports.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Oreports.setMaximumSize(new java.awt.Dimension(200, 200));
        bt_Oreports.setMinimumSize(new java.awt.Dimension(200, 200));
        bt_Oreports.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        bt_Oreports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OreportsActionPerformed(evt);
            }
        });
        jp_OmainMenu.add(bt_Oreports, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 333, 200, 200));

        jPanel4.setBackground(new java.awt.Color(0, 200, 83));
        jPanel4.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel4.setMinimumSize(new java.awt.Dimension(200, 200));

        lb_customerCount2.setBackground(new java.awt.Color(255, 255, 255));
        lb_customerCount2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_customerCount2.setForeground(new java.awt.Color(255, 255, 255));
        lb_customerCount2.setText("FOP");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Time");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date");

        lb_funderCount2.setBackground(new java.awt.Color(255, 255, 255));
        lb_funderCount2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_funderCount2.setForeground(new java.awt.Color(255, 255, 255));
        lb_funderCount2.setText("CIP");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lb_funderCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lb_customerCount2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(93, 93, 93))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_customerCount2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_funderCount2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jp_OmainMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 115, -1, 200));

        jPanel5.setBackground(new java.awt.Color(0, 200, 83));
        jPanel5.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel5.setMinimumSize(new java.awt.Dimension(200, 200));

        lb_customerCount3.setBackground(new java.awt.Color(255, 255, 255));
        lb_customerCount3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_customerCount3.setForeground(new java.awt.Color(255, 255, 255));
        lb_customerCount3.setText("CCT");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Time");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Date");

        lb_funderCount3.setBackground(new java.awt.Color(255, 255, 255));
        lb_funderCount3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_funderCount3.setForeground(new java.awt.Color(255, 255, 255));
        lb_funderCount3.setText("FCT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lb_customerCount3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_funderCount3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_customerCount3)
                    .addComponent(lb_funderCount3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jp_OmainMenu.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 333, -1, 200));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/Vector-PNG-Pictureright.png"))); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jp_OmainMenu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/vt.png"))); // NOI18N
        jp_OmainMenu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 94, 390, 510));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pl_systemExit.setBackground(new java.awt.Color(33, 33, 33));
        pl_systemExit.setLayout(new java.awt.CardLayout());

        jl_systemExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_systemExit.setForeground(new java.awt.Color(255, 255, 255));
        jl_systemExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_systemExit.setText("X");
        jl_systemExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jl_systemExitMouseMoved(evt);
            }
        });
        jl_systemExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_systemExitMouseClicked(evt);
            }
        });
        pl_systemExit.add(jl_systemExit, "card2");

        getContentPane().add(pl_systemExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1275, 23, 25, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Softidea Solution (Pvt) Ltd.");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1054, 680, 200, -1));

        lb_wk_option1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option1.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option1.setText("Home");
        lb_wk_option1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_option1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_option1MouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 145, 35));

        lb_wk_option2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option2.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option2.setText("Customer");
        lb_wk_option2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_option2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_option2MouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 145, 35));

        lb_wk_option3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option3.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option3.setText("Fund");
        lb_wk_option3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_option3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_option3MouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 145, 35));

        lb_wk_option4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option4.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option4.setText("Installment");
        lb_wk_option4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_option4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 145, 35));

        lb_wk_option5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option5.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option5.setText("Cash Account");
        lb_wk_option5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_option5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 145, 35));

        lb_wk_option6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option6.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option6.setText("Pendding Customer");
        lb_wk_option6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_option6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 145, 35));

        lb_wk_option8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option8.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option8.setText("My Account");
        lb_wk_option8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_option8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_option8MouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_option8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 145, 35));

        lb_wk_option7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_option7.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_option7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_option7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_option7.setText("Close Customer");
        lb_wk_option7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_option7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_option7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 145, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Administrator | Work Area");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/private_access/images/frame_admin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        jp_adminMainPanel.setBackground(new java.awt.Color(102, 102, 102));
        jp_adminMainPanel.setFocusCycleRoot(true);
        jp_adminMainPanel.setPreferredSize(new java.awt.Dimension(1300, 400));
        jp_adminMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton1.setText("User Managment");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 115, 200, 200));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton2.setText("Customer Managment");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton2.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 115, 200, 200));

        jButton3.setBackground(new java.awt.Color(0, 153, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton3.setText("Fund Managment");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton3.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 115, 200, 200));

        jButton4.setBackground(new java.awt.Color(0, 153, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton4.setText("Installment Management");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton4.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 115, 200, 200));

        jButton6.setBackground(new java.awt.Color(0, 153, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton6.setText("Cash Management");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton6.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 333, 200, 200));

        jButton7.setBackground(new java.awt.Color(0, 153, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton7.setText("Loan Managment");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton7.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 333, 200, 200));

        jButton8.setBackground(new java.awt.Color(0, 153, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton8.setText("Administrator Managment");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton8.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 333, 200, 200));

        jButton9.setBackground(new java.awt.Color(0, 153, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton9.setText("Reports Managment");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton9.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 333, 200, 200));

        jPanel2.setBackground(new java.awt.Color(0, 200, 83));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 200));

        lb_customerCount1.setBackground(new java.awt.Color(255, 255, 255));
        lb_customerCount1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_customerCount1.setForeground(new java.awt.Color(255, 255, 255));
        lb_customerCount1.setText("FOP");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Time");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date");

        lb_funderCount1.setBackground(new java.awt.Color(255, 255, 255));
        lb_funderCount1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_funderCount1.setForeground(new java.awt.Color(255, 255, 255));
        lb_funderCount1.setText("CIP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_funderCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_customerCount1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(93, 93, 93))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_customerCount1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_funderCount1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jp_adminMainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 115, -1, 200));

        jPanel1.setBackground(new java.awt.Color(0, 200, 83));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));

        lb_customerCount.setBackground(new java.awt.Color(255, 255, 255));
        lb_customerCount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_customerCount.setForeground(new java.awt.Color(255, 255, 255));
        lb_customerCount.setText("CCT");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date");

        lb_funderCount.setBackground(new java.awt.Color(255, 255, 255));
        lb_funderCount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_funderCount.setForeground(new java.awt.Color(255, 255, 255));
        lb_funderCount.setText("FCT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_customerCount, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_funderCount, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_customerCount)
                    .addComponent(lb_funderCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jp_adminMainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 333, -1, 200));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/Vector-PNG-Pictureright.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jp_adminMainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/vt.png"))); // NOI18N
        jp_adminMainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 94, 390, 510));

        getContentPane().add(jp_adminMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1300, 600));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/private_access/images/under_frame.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1300, 30));

        setSize(new java.awt.Dimension(1300, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jl_systemExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_systemExitMouseMoved

        pl_systemExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

    }//GEN-LAST:event_jl_systemExitMouseMoved

    private void jl_systemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_systemExitMouseClicked

        //System.exit(0);
        this.dispose();
        user_login uslg = new user_login();
        uslg.setVisible(true);

    }//GEN-LAST:event_jl_systemExitMouseClicked

    private void lb_wk_option2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_option2MouseClicked


    }//GEN-LAST:event_lb_wk_option2MouseClicked

    private void lb_wk_option8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_option8MouseClicked

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_customerSettings settings = new Admin_customerSettings();
            settings.setVisible(true);
            jp_adminMainPanel.add(settings);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_lb_wk_option8MouseClicked

    private void lb_wk_option3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_option3MouseClicked


    }//GEN-LAST:event_lb_wk_option3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lb_wk_option1.setVisible(true);
        load_user_managment();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().browse(new URI("http://www.fsczone.com/"));
            }
        } catch (URISyntaxException | IOException e) {
        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void lb_wk_option1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_option1MouseClicked

        lb_wk_option1.setVisible(false);
        
        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            jp_OmainMenu.setVisible(true);
            jp_adminMainPanel.add(jp_OmainMenu);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_lb_wk_option1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lb_wk_option1.setVisible(true);
        load_customer_managment();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        lb_wk_option1.setVisible(true);
        load_fundManagment();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        lb_wk_option1.setVisible(true);
        load_installmentManagment();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        lb_wk_option1.setVisible(true);
        load_cashManagment();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        lb_wk_option1.setVisible(true);
        load_loanManagment();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        lb_wk_option1.setVisible(true);
        load_admin_managment();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        lb_wk_option1.setVisible(true);
        load_reportManagment();

    }//GEN-LAST:event_jButton9ActionPerformed

    private void bt_OuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OuserActionPerformed
        lb_wk_option1.setVisible(true);
        load_user_managment();
    }//GEN-LAST:event_bt_OuserActionPerformed

    private void bt_OcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OcustomerActionPerformed
        lb_wk_option1.setVisible(true);
        load_customer_managment();
    }//GEN-LAST:event_bt_OcustomerActionPerformed

    private void bt_OfundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OfundActionPerformed
        lb_wk_option1.setVisible(true);
        load_fundManagment();
    }//GEN-LAST:event_bt_OfundActionPerformed

    private void bt_OinstallmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OinstallmentActionPerformed
        lb_wk_option1.setVisible(true);
        load_installmentManagment();
    }//GEN-LAST:event_bt_OinstallmentActionPerformed

    private void bt_OcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OcashActionPerformed
        lb_wk_option1.setVisible(true);
        load_cashManagment();
    }//GEN-LAST:event_bt_OcashActionPerformed

    private void bt_OloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OloanActionPerformed
        lb_wk_option1.setVisible(true);
        load_loanManagment();
    }//GEN-LAST:event_bt_OloanActionPerformed

    private void bt_OadministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OadministratorActionPerformed
        lb_wk_option1.setVisible(true);
        load_admin_managment();
    }//GEN-LAST:event_bt_OadministratorActionPerformed

    private void bt_OreportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OreportsActionPerformed
        lb_wk_option1.setVisible(true);
        load_reportManagment();
    }//GEN-LAST:event_bt_OreportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin_workArea().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Oadministrator;
    private javax.swing.JButton bt_Ocash;
    private javax.swing.JButton bt_Ocustomer;
    private javax.swing.JButton bt_Ofund;
    private javax.swing.JButton bt_Oinstallment;
    private javax.swing.JButton bt_Oloan;
    private javax.swing.JButton bt_Oreports;
    private javax.swing.JButton bt_Ouser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jl_systemExit;
    public javax.swing.JPanel jp_OmainMenu;
    public static javax.swing.JPanel jp_adminMainPanel;
    private javax.swing.JLabel lb_customerCount;
    private javax.swing.JLabel lb_customerCount1;
    private javax.swing.JLabel lb_customerCount2;
    private javax.swing.JLabel lb_customerCount3;
    private javax.swing.JLabel lb_funderCount;
    private javax.swing.JLabel lb_funderCount1;
    private javax.swing.JLabel lb_funderCount2;
    private javax.swing.JLabel lb_funderCount3;
    public static javax.swing.JLabel lb_wk_option1;
    public static javax.swing.JLabel lb_wk_option2;
    public static javax.swing.JLabel lb_wk_option3;
    public static javax.swing.JLabel lb_wk_option4;
    public static javax.swing.JLabel lb_wk_option5;
    public static javax.swing.JLabel lb_wk_option6;
    public static javax.swing.JLabel lb_wk_option7;
    public static javax.swing.JLabel lb_wk_option8;
    private javax.swing.JPanel pl_systemExit;
    // End of variables declaration//GEN-END:variables

    private void load_user_managment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_userManagment user = new Admin_userManagment();
            user.setVisible(true);
            jp_adminMainPanel.add(user);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void load_fundManagment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_fundManagment ai = new Admin_fundManagment();
            ai.setVisible(true);
            jp_adminMainPanel.add(ai);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void load_installmentManagment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_installmentManagment am = new Admin_installmentManagment();
            am.setVisible(true);
            jp_adminMainPanel.add(am);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void loadCusFundCount() {
        try {
            ResultSet rs = MC_DB.myConnection().createStatement().executeQuery("SELECT COUNT(DISTINCT idcustomer) AS NumberOfCustomers FROM customer;");
            //ResultSet r2=MC_DB.myConnection().createStatement().executeQuery("SELECT COUNT(DISTINCT idfunder) AS NumberOfFunders FROM funder;");
            ResultSet r2 = MC_DB.myConnection().createStatement().executeQuery("SELECT COUNT(idfunder) AS numffunders FROM funder;");
            while (rs.next()) {
                String cusCount = rs.getString("NumberOfCustomers");
                lb_customerCount.setText(cusCount);

            }
//            while (r2.next()) {                
//                String funderCount=rs.getString("numffunders");
//                lb_funderCount.setText(funderCount+"");
//            }

        } catch (SQLException ex) {
            Logger.getLogger(Admin_workArea.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void load_admin_managment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_adminManagment aiq = new Admin_adminManagment();
            aiq.setVisible(true);
            jp_adminMainPanel.add(aiq);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void load_customer_managment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_customerManagment cus_add = new Admin_customerManagment();
            cus_add.setVisible(true);
            jp_adminMainPanel.add(cus_add);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void md_HomeMenuVisibleLabel(boolean visible) {

        lb_wk_option1.setVisible(visible);
        lb_wk_option2.setVisible(visible);
        lb_wk_option3.setVisible(visible);
        lb_wk_option4.setVisible(visible);
        lb_wk_option5.setVisible(visible);
        lb_wk_option6.setVisible(visible);
        lb_wk_option7.setVisible(visible);
        lb_wk_option8.setVisible(visible);

    }

    private void load_cashManagment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_cashManagment am = new Admin_cashManagment();
            am.setVisible(true);
            jp_adminMainPanel.add(am);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void load_loanManagment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_loanManagment am = new Admin_loanManagment();
            am.setVisible(true);
            jp_adminMainPanel.add(am);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void load_reportManagment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_reportManagment am = new Admin_reportManagment();
            am.setVisible(true);
            jp_adminMainPanel.add(am);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
