/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softidea.www.private_access.adminstrator;

import com.fsczone.www.lookAndFeel.pro_lookandfeel;
import com.softidea.www.public_access.login_user.user_login;
import com.softidea.www.public_connection.MC_DB;
import com.sun.awt.AWTUtilities;
import java.awt.Desktop;
import java.awt.FlowLayout;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author deepalsuranga
 */
public class Admin_workArea extends javax.swing.JFrame {

    /**
     * Creates new form admin_index
     */
    public Admin_workArea() {
        initComponents();
        md_HomeMenuVisibleLabel(false);
        try {
            AWTUtilities.setWindowOpaque(this, false);
        } catch (Exception e) {
        }
        pro_lookandfeel.Set();

        loadCusFundCount();

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pl_systemExit = new javax.swing.JPanel();
        jl_systemExit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_wk_home = new javax.swing.JLabel();
        lb_wk_customer = new javax.swing.JLabel();
        lb_wk_fund = new javax.swing.JLabel();
        lb_wk_installment = new javax.swing.JLabel();
        lb_wk_cashaccount = new javax.swing.JLabel();
        lb_wk_cus_pendding = new javax.swing.JLabel();
        lb_wk_myaccount = new javax.swing.JLabel();
        lb_wk_cus_closecustomer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jp_adminMainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb_customerCount1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_funderCount1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_customerCount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_funderCount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pl_systemExit.setBackground(new java.awt.Color(33, 33, 33));
        pl_systemExit.setLayout(new java.awt.CardLayout());

        jl_systemExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_systemExit.setForeground(new java.awt.Color(255, 255, 255));
        jl_systemExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_systemExit.setText("X");
        jl_systemExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jl_systemExitMouseMoved(evt);
            }
        });
        jl_systemExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_systemExitMouseClicked(evt);
            }
        });
        pl_systemExit.add(jl_systemExit, "card2");

        getContentPane().add(pl_systemExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1275, 23, 25, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Softidea Solution (Pvt) Ltd.");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1054, 680, 200, -1));

        lb_wk_home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_home.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_home.setText("Home");
        lb_wk_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_homeMouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 145, 35));

        lb_wk_customer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_customer.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_customer.setText("Customer");
        lb_wk_customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_customer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_customerMouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 145, 35));

        lb_wk_fund.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_fund.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_fund.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_fund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_fund.setText("Fund");
        lb_wk_fund.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_fund.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_fund.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_fundMouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_fund, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 145, 35));

        lb_wk_installment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_installment.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_installment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_installment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_installment.setText("Installment");
        lb_wk_installment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_installment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_installment, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 145, 35));

        lb_wk_cashaccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_cashaccount.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_cashaccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_cashaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_cashaccount.setText("Cash Account");
        lb_wk_cashaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_cashaccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_cashaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 145, 35));

        lb_wk_cus_pendding.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_cus_pendding.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_cus_pendding.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_cus_pendding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_cus_pendding.setText("Pendding Customer");
        lb_wk_cus_pendding.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_cus_pendding.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_cus_pendding, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 145, 35));

        lb_wk_myaccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_myaccount.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_myaccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_myaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_myaccount.setText("My Account");
        lb_wk_myaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_myaccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_wk_myaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_wk_myaccountMouseClicked(evt);
            }
        });
        getContentPane().add(lb_wk_myaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 145, 35));

        lb_wk_cus_closecustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_wk_cus_closecustomer.setForeground(new java.awt.Color(255, 255, 255));
        lb_wk_cus_closecustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wk_cus_closecustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        lb_wk_cus_closecustomer.setText("Close Customer");
        lb_wk_cus_closecustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_wk_cus_closecustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_wk_cus_closecustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 145, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Administrator | Work Area");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/private_access/images/frame_admin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        jp_adminMainPanel.setBackground(new java.awt.Color(102, 102, 102));
        jp_adminMainPanel.setFocusCycleRoot(true);
        jp_adminMainPanel.setPreferredSize(new java.awt.Dimension(1300, 400));
        jp_adminMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton1.setText("User Managment");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 115, 200, 200));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton2.setText("Customer Managment");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton2.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 115, 200, 200));

        jButton3.setBackground(new java.awt.Color(0, 153, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton3.setText("Fund Managment");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton3.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 115, 200, 200));

        jButton4.setBackground(new java.awt.Color(0, 153, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton4.setText("Installment Management");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton4.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 115, 200, 200));

        jButton6.setBackground(new java.awt.Color(0, 153, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton6.setText("Cash Management");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton6.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 333, 200, 200));

        jButton7.setBackground(new java.awt.Color(0, 153, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton7.setText("Loan Managment");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton7.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 333, 200, 200));

        jButton8.setBackground(new java.awt.Color(0, 153, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton8.setText("Administrator Managment");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton8.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 333, 200, 200));

        jButton9.setBackground(new java.awt.Color(0, 153, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu_in.png"))); // NOI18N
        jButton9.setText("Reports Managment");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setMaximumSize(new java.awt.Dimension(200, 200));
        jButton9.setMinimumSize(new java.awt.Dimension(200, 200));
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/admin_buttonMenu.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jp_adminMainPanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 333, 200, 200));

        jPanel2.setBackground(new java.awt.Color(0, 200, 83));
        jPanel2.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 200));

        lb_customerCount1.setBackground(new java.awt.Color(255, 255, 255));
        lb_customerCount1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_customerCount1.setForeground(new java.awt.Color(255, 255, 255));
        lb_customerCount1.setText("FOP");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Time");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date");

        lb_funderCount1.setBackground(new java.awt.Color(255, 255, 255));
        lb_funderCount1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_funderCount1.setForeground(new java.awt.Color(255, 255, 255));
        lb_funderCount1.setText("CIP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_funderCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_customerCount1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(93, 93, 93))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_customerCount1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_funderCount1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jp_adminMainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 115, -1, 200));

        jPanel1.setBackground(new java.awt.Color(0, 200, 83));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));

        lb_customerCount.setBackground(new java.awt.Color(255, 255, 255));
        lb_customerCount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_customerCount.setForeground(new java.awt.Color(255, 255, 255));
        lb_customerCount.setText("CCT");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date");

        lb_funderCount.setBackground(new java.awt.Color(255, 255, 255));
        lb_funderCount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_funderCount.setForeground(new java.awt.Color(255, 255, 255));
        lb_funderCount.setText("FCT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_customerCount, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_funderCount, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_customerCount)
                    .addComponent(lb_funderCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jp_adminMainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 333, -1, 200));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/Vector-PNG-Pictureright.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jp_adminMainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/vt.png"))); // NOI18N
        jp_adminMainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 94, 390, 510));

        getContentPane().add(jp_adminMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1300, 600));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/private_access/images/under_frame.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1300, 30));

        setSize(new java.awt.Dimension(1300, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jl_systemExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_systemExitMouseMoved

        pl_systemExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

    }//GEN-LAST:event_jl_systemExitMouseMoved

    private void jl_systemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_systemExitMouseClicked

        //System.exit(0);
        this.dispose();
        user_login uslg = new user_login();
        uslg.setVisible(true);

    }//GEN-LAST:event_jl_systemExitMouseClicked

    private void lb_wk_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_customerMouseClicked


    }//GEN-LAST:event_lb_wk_customerMouseClicked

    private void lb_wk_myaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_myaccountMouseClicked

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_customerSettings settings = new Admin_customerSettings();
            settings.setVisible(true);
            jp_adminMainPanel.add(settings);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_lb_wk_myaccountMouseClicked

    private void lb_wk_fundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_fundMouseClicked


    }//GEN-LAST:event_lb_wk_fundMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        load_user_managment();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        try {
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().browse(new URI("http://www.fsczone.com/"));
            }
        } catch (URISyntaxException | IOException e) {
        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void lb_wk_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_wk_homeMouseClicked

        this.dispose();
        Admin_workArea admin = new Admin_workArea();
        admin.setVisible(true);


    }//GEN-LAST:event_lb_wk_homeMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        load_customerPanel();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        load_fundManagment();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        load_installmentManagment();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        load_admin_managment();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin_workArea().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jl_systemExit;
    public static javax.swing.JPanel jp_adminMainPanel;
    private javax.swing.JLabel lb_customerCount;
    private javax.swing.JLabel lb_customerCount1;
    private javax.swing.JLabel lb_funderCount;
    private javax.swing.JLabel lb_funderCount1;
    private javax.swing.JLabel lb_wk_cashaccount;
    private javax.swing.JLabel lb_wk_cus_closecustomer;
    private javax.swing.JLabel lb_wk_cus_pendding;
    private javax.swing.JLabel lb_wk_customer;
    private javax.swing.JLabel lb_wk_fund;
    private javax.swing.JLabel lb_wk_home;
    private javax.swing.JLabel lb_wk_installment;
    private javax.swing.JLabel lb_wk_myaccount;
    private javax.swing.JPanel pl_systemExit;
    // End of variables declaration//GEN-END:variables

    private void load_customerPanel() {
        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            jp_customer_add cus_add = new jp_customer_add();
            cus_add.setVisible(true);
            jp_adminMainPanel.add(cus_add);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void load_user_managment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_userManagment user = new Admin_userManagment("user");
            user.setVisible(true);
            jp_adminMainPanel.add(user);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void load_fundManagment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_funderInformation ai = new Admin_funderInformation();
            ai.setVisible(true);
            jp_adminMainPanel.add(ai);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void load_installmentManagment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_installmentManagment am = new Admin_installmentManagment();
            am.setVisible(true);
            jp_adminMainPanel.add(am);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void loadCusFundCount() {
        try {
            ResultSet rs = MC_DB.myConnection().createStatement().executeQuery("SELECT COUNT(DISTINCT idcustomer) AS NumberOfCustomers FROM customer;");
            //ResultSet r2=MC_DB.myConnection().createStatement().executeQuery("SELECT COUNT(DISTINCT idfunder) AS NumberOfFunders FROM funder;");
            ResultSet r2 = MC_DB.myConnection().createStatement().executeQuery("SELECT COUNT(idfunder) AS numffunders FROM funder;");
            while (rs.next()) {
                String cusCount = rs.getString("NumberOfCustomers");
                lb_customerCount.setText(cusCount);

            }
//            while (r2.next()) {                
//                String funderCount=rs.getString("numffunders");
//                lb_funderCount.setText(funderCount+"");
//            }

        } catch (SQLException ex) {
            Logger.getLogger(Admin_workArea.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void load_admin_managment() {

        try {
            jp_adminMainPanel.removeAll();
            jp_adminMainPanel.setLayout(new FlowLayout());
            Admin_userManagment aiq = new Admin_userManagment("admin");
            aiq.setVisible(true);
            jp_adminMainPanel.add(aiq);
            jp_adminMainPanel.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void md_HomeMenuVisibleLabel(boolean visible) {

        lb_wk_home.setVisible(visible);
        lb_wk_customer.setVisible(visible);
        lb_wk_fund.setVisible(visible);
        lb_wk_installment.setVisible(visible);
        lb_wk_cashaccount.setVisible(visible);
        lb_wk_cus_pendding.setVisible(visible);
        lb_wk_cus_closecustomer.setVisible(visible);
        lb_wk_myaccount.setVisible(visible);

    }
}
