/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softidea.www.private_access.adminstrator;

import com.fsczone.www.lookAndFeel.pro_lookandfeel;
import com.softidea.www.private_access.methods.md_cus;
import com.softidea.www.private_access.methods.md_loans;
import com.softidea.www.public_connection.MC_DB;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deepalsuranga
 */
public class Admin_customerManagment extends javax.swing.JPanel {

    /**
     * Creates new form jp_customer_add
     */
    public Admin_customerManagment() {

        initComponents();
        pro_lookandfeel.Set();
        bt_updateCustomer.setEnabled(false);
        tf_nic.grabFocus();

        md_loadFunder();
        md_tb_loadCustomer();

        //DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        //get current date time with Date()
        Date date = new Date();
        dc_registrationDate.setDate(date);
        md_genLoadId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tf_contact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rb_male = new javax.swing.JRadioButton();
        tf_address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        rb_female = new javax.swing.JRadioButton();
        tf_nic = new javax.swing.JTextField();
        bt_search = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_period = new javax.swing.JTextField();
        tf_loanAmount = new javax.swing.JTextField();
        bt_addLoan = new javax.swing.JButton();
        cb_selectFunder_customer = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_customerAddView = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tf_loanNumber = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_extraInterest = new javax.swing.JTextField();
        dc_registrationDate = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        cb_selectFund = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cb_periodType = new javax.swing.JComboBox();
        cb_mainInstallmentPeriodType = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_v_loanAmount = new javax.swing.JLabel();
        lb_v_totalAmount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lb_v_installment = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lb_v_profit = new javax.swing.JLabel();
        lb_v_period = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_v_finalDate = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        bt_updateCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(66, 66, 66));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address:");

        tf_contact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_contact.setPreferredSize(new java.awt.Dimension(300, 40));
        tf_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_contactKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_contactKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Customer Name :");

        genderGroup.add(rb_male);
        rb_male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_male.setForeground(new java.awt.Color(255, 255, 255));
        rb_male.setText("Male");
        rb_male.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        rb_male.setContentAreaFilled(false);
        rb_male.setFocusPainted(false);
        rb_male.setFocusable(false);
        rb_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_maleActionPerformed(evt);
            }
        });
        rb_male.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rb_maleKeyReleased(evt);
            }
        });

        tf_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_addressKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIC Number :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact No :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender :");

        tf_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_nameKeyReleased(evt);
            }
        });

        genderGroup.add(rb_female);
        rb_female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_female.setForeground(new java.awt.Color(255, 255, 255));
        rb_female.setText("Female");
        rb_female.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        rb_female.setContentAreaFilled(false);
        rb_female.setFocusPainted(false);
        rb_female.setFocusable(false);
        rb_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femaleActionPerformed(evt);
            }
        });
        rb_female.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rb_femaleKeyReleased(evt);
            }
        });

        tf_nic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_nicKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nicKeyTyped(evt);
            }
        });

        bt_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/home/images/Google Web Search_40.png"))); // NOI18N
        bt_search.setBorderPainted(false);
        bt_search.setContentAreaFilled(false);
        bt_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tf_nic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb_male, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_female, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_address)
                    .addComponent(tf_name))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_male, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_female, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(66, 66, 66));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Registration Date:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Loan Amount :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Period :(Hit Enter)");

        tf_period.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_periodActionPerformed(evt);
            }
        });
        tf_period.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_periodKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_periodKeyTyped(evt);
            }
        });

        tf_loanAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_loanAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_loanAmountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_loanAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_loanAmountKeyTyped(evt);
            }
        });

        bt_addLoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_addLoan.setForeground(new java.awt.Color(255, 255, 255));
        bt_addLoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButtonNormal.png"))); // NOI18N
        bt_addLoan.setText("Add Loan");
        bt_addLoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_addLoan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButtonHover.png"))); // NOI18N
        bt_addLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addLoanActionPerformed(evt);
            }
        });

        cb_selectFunder_customer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_selectFunder_customer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Funder" }));
        cb_selectFunder_customer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_selectFunder_customerItemStateChanged(evt);
            }
        });
        cb_selectFunder_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_selectFunder_customerMouseClicked(evt);
            }
        });
        cb_selectFunder_customer.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_selectFunder_customerPropertyChange(evt);
            }
        });
        cb_selectFunder_customer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cb_selectFunder_customerKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Select Funder:");

        tb_customerAddView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Customer Name", "Regidtation Date", "Loan Amount", "Due Amount", "Due Period"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_customerAddView);
        if (tb_customerAddView.getColumnModel().getColumnCount() > 0) {
            tb_customerAddView.getColumnModel().getColumn(0).setResizable(false);
            tb_customerAddView.getColumnModel().getColumn(0).setPreferredWidth(4);
        }

        jPanel1.setBackground(new java.awt.Color(91, 91, 91));
        jPanel1.setForeground(new java.awt.Color(91, 91, 91));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Loan No :");

        tf_loanNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_loanNumber.setText("LON-W-00000000-00000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_loanNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_loanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Extra Interest :");

        tf_extraInterest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_extraInterest.setPreferredSize(new java.awt.Dimension(300, 40));
        tf_extraInterest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_extraInterestKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_extraInterestKeyTyped(evt);
            }
        });

        dc_registrationDate.setDateFormatString("yyyy-MM-dd");
        dc_registrationDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dc_registrationDate.setMinSelectableDate(new java.util.Date(-62135785690000L));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Select Fund:");

        cb_selectFund.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_selectFund.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Fund" }));
        cb_selectFund.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cb_selectFundKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Main Installment Period Type:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Period Type:");

        cb_periodType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_periodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "With Out Saturday(Week days)", "With Saturday" }));
        cb_periodType.setEnabled(false);
        cb_periodType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_periodTypeItemStateChanged(evt);
            }
        });

        cb_mainInstallmentPeriodType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_mainInstallmentPeriodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dailly", "Weekly", "Monthly" }));
        cb_mainInstallmentPeriodType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cb_mainInstallmentPeriodTypeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_selectFunder_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_selectFund, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_loanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_extraInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_periodType, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_period, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_registrationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_addLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_mainInstallmentPeriodType, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(6, 6, 6)
                        .addComponent(cb_selectFunder_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(6, 6, 6)
                        .addComponent(cb_selectFund, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18)
                        .addGap(6, 6, 6)
                        .addComponent(tf_loanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel19)
                        .addGap(5, 5, 5)
                        .addComponent(tf_extraInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(4, 4, 4)
                        .addComponent(cb_mainInstallmentPeriodType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_periodType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(7, 7, 7)
                        .addComponent(tf_period, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(dc_registrationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(bt_addLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loan Amount :");

        lb_v_loanAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_v_loanAmount.setForeground(new java.awt.Color(0, 204, 0));
        lb_v_loanAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_v_loanAmount.setText("0.00");

        lb_v_totalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_v_totalAmount.setForeground(new java.awt.Color(0, 204, 0));
        lb_v_totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_v_totalAmount.setText("0.00");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Installment :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total Payble Amount:");

        lb_v_installment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_v_installment.setForeground(new java.awt.Color(255, 102, 0));
        lb_v_installment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_v_installment.setText("0.00");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Profit :");

        lb_v_profit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_v_profit.setForeground(new java.awt.Color(255, 0, 0));
        lb_v_profit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_v_profit.setText("0.00");

        lb_v_period.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_v_period.setForeground(new java.awt.Color(255, 255, 0));
        lb_v_period.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_v_period.setText("0.00");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Period :");

        lb_v_finalDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_v_finalDate.setForeground(new java.awt.Color(255, 255, 255));
        lb_v_finalDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_v_finalDate.setText("0000-00-00");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("End Date:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lb_v_period, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lb_v_installment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_v_profit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_v_totalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_v_loanAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_v_finalDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_v_loanAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_v_totalAmount)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_v_period)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_v_installment)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_v_profit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(lb_v_finalDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        bt_updateCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_updateCustomer.setForeground(new java.awt.Color(255, 255, 255));
        bt_updateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButtonNormal.png"))); // NOI18N
        bt_updateCustomer.setText("Update Customer");
        bt_updateCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_updateCustomer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButtonHover.png"))); // NOI18N
        bt_updateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_updateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_updateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rb_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_maleActionPerformed

    }//GEN-LAST:event_rb_maleActionPerformed

    private void rb_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femaleActionPerformed

    }//GEN-LAST:event_rb_femaleActionPerformed

    private void bt_addLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addLoanActionPerformed

        int isOK = JOptionPane.showConfirmDialog(this, "Are you Sure?", "Confrom", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        md_profitCalculation();
        if (isOK == JOptionPane.YES_OPTION) {

            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String today_date = sdf.format(d);

            try {
                String gender = "male";
                if (Admin_customerManagment.rb_male.isSelected()) {
                    gender = "male";
                } else if (Admin_customerManagment.rb_female.isSelected()) {
                    gender = "female";
                }

                ///////////////////////////////////
                String gen_loan_id = tf_loanNumber.getText().toUpperCase();

                ////////////////////////////////////////////////////////////////
                try {
                    ResultSet rs = MC_DB.myConnection().createStatement().executeQuery("SELECT e.`funder_name`, e.`idfunder`, u.`fund`, u.`fund_date`,u.`idfund` FROM `funder` AS e LEFT JOIN `fund` AS u ON e.`idfunder` = u.`funder_idfunder`;");
                    ResultSet rs_idFunder = MC_DB.myConnection().createStatement().executeQuery("SELECT * from funder where idfunder='" + md_funderID() + "' ");
                } catch (SQLException ex) {
                    Logger.getLogger(Admin_customerManagment.class.getName()).log(Level.SEVERE, null, ex);
                }

                //////////////////////////////////////////////////////////
                String idwithFund = cb_selectFund.getSelectedItem().toString();

                if (cb_selectFund.getSelectedIndex() == 0) {
                    cb_periodType.setEnabled(true);
                } else {
                    cb_periodType.setEnabled(false);
                    lb_v_finalDate.setText("");
                }

                int fundID = 0;
                try {
                    String[] id = idwithFund.split("-", 0);
                    if (id != null) {

                        fundID = Integer.parseInt(id[0]);

                    }
                } catch (NumberFormatException e) {
                }

                /////////////////////////////////////////////////////
                //DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                //get current date time with Date()
                Date date = new Date();
                dc_registrationDate.setDate(date);

                ///////////////////////////////////////////////////////   
                boolean isture = md_cus.saveCustomer(
                        tf_nic.getText().toLowerCase(),
                        tf_name.getText().toLowerCase(),
                        tf_address.getText().toLowerCase(),
                        tf_contact.getText().toLowerCase(),
                        gender,
                        gen_loan_id,
                        dc_registrationDate.getDate().toString(),
                        tf_loanAmount.getText().trim(),
                        cb_mainInstallmentPeriodType.getSelectedItem().toString(),
                        tf_period.getText(),
                        lb_v_installment.getText(),
                        tf_extraInterest.getText(),
                        lb_v_totalAmount.getText(),
                        "active",
                        fundID + "",
                        md_funderID()
                );

                JOptionPane.showMessageDialog(this, fundID);
               md_loans.minToFunderFund(fundID, lb_v_loanAmount.getText());
                if (isture == true) {
                    JOptionPane.showMessageDialog(this, "Customer And Loan Successfully \n Saved!");
                    md_genLoadId();
                } else {
                    JOptionPane.showMessageDialog(this, "Customer And Loan  \n Not Saved!");
                }

            } catch (HeadlessException e) {
                e.printStackTrace();
            }

        } else if (isOK == JOptionPane.NO_OPTION) {
            md_profitCalculation();
        }


    }//GEN-LAST:event_bt_addLoanActionPerformed

    private void tf_loanAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_loanAmountKeyReleased

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            tf_extraInterest.grabFocus();
        }

    }//GEN-LAST:event_tf_loanAmountKeyReleased

    private void tf_nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nicKeyReleased

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {

            tf_name.grabFocus();
        }

    }//GEN-LAST:event_tf_nicKeyReleased

    private void tf_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nameKeyReleased

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            tf_address.grabFocus();
        }

    }//GEN-LAST:event_tf_nameKeyReleased

    private void tf_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_addressKeyReleased

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            rb_male.isSelected();
        }

    }//GEN-LAST:event_tf_addressKeyReleased

    private void rb_maleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_maleKeyReleased

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            tf_contact.grabFocus();
        }

    }//GEN-LAST:event_rb_maleKeyReleased

    private void rb_femaleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_femaleKeyReleased

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            tf_contact.grabFocus();
        }

    }//GEN-LAST:event_rb_femaleKeyReleased

    private void tf_periodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_periodActionPerformed


    }//GEN-LAST:event_tf_periodActionPerformed

    private void tf_periodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_periodKeyReleased

        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {

            md_profitCalculation();
            calDate();
        }

    }//GEN-LAST:event_tf_periodKeyReleased

    private void cb_selectFunder_customerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_selectFunder_customerPropertyChange


    }//GEN-LAST:event_cb_selectFunder_customerPropertyChange

    private void cb_selectFunder_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_selectFunder_customerMouseClicked


    }//GEN-LAST:event_cb_selectFunder_customerMouseClicked

    private void cb_selectFunder_customerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_selectFunder_customerItemStateChanged

        loadFund(md_funderID());

    }//GEN-LAST:event_cb_selectFunder_customerItemStateChanged


    private void tf_loanAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_loanAmountKeyPressed


    }//GEN-LAST:event_tf_loanAmountKeyPressed

    private void cb_periodTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_periodTypeItemStateChanged

        md_genLoadId();

    }//GEN-LAST:event_cb_periodTypeItemStateChanged

    private void tf_contactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_contactKeyReleased

        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            cb_selectFunder_customer.grabFocus();
        }


    }//GEN-LAST:event_tf_contactKeyReleased

    private void cb_selectFunder_customerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_selectFunder_customerKeyReleased

        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            cb_selectFund.grabFocus();
        }

    }//GEN-LAST:event_cb_selectFunder_customerKeyReleased

    private void cb_selectFundKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_selectFundKeyReleased

        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            tf_loanAmount.grabFocus();
        }

    }//GEN-LAST:event_cb_selectFundKeyReleased

    private void tf_extraInterestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_extraInterestKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_extraInterestKeyReleased

    private void cb_mainInstallmentPeriodTypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_mainInstallmentPeriodTypeKeyReleased

        if (cb_mainInstallmentPeriodType.getSelectedIndex() == 0) {
            cb_periodType.setEnabled(true);

        }


    }//GEN-LAST:event_cb_mainInstallmentPeriodTypeKeyReleased

    private void bt_updateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateCustomerActionPerformed

        md_updateCustomer();
        bt_updateCustomer.setEnabled(false);

    }//GEN-LAST:event_bt_updateCustomerActionPerformed

    String localNIC = "";
    String databaseNIC = "";
    String dbfullname = "";
    String dbaddress = "";
    String dbcontact = "";
    String dbgender = "";

    String gt_nic = "";
    String gt_fullname = "";
    String gt_address = "";
    String gt_contact = "";
    String gt_gender = "male";

    private void bt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_searchActionPerformed
        localNIC = tf_nic.getText().trim().toLowerCase();

        gt_nic = tf_nic.getText().toLowerCase().trim();
        gt_fullname = tf_name.getText().trim();
        gt_address = tf_address.getText().trim();
        gt_contact = tf_contact.getText().trim();

        try {

            ResultSet search_nic = MC_DB.search_dataOne("customer", "cus_nic", localNIC);
            while (search_nic.next()) {
                databaseNIC = search_nic.getString("cus_nic");
                dbfullname = search_nic.getString("cus_fullname");
                dbaddress = search_nic.getString("cus_address");
                dbcontact = search_nic.getString("cus_contact");
                dbgender = search_nic.getString("cus_gender");
            }
            if (!(dbfullname.isEmpty() && dbaddress.isEmpty() && dbcontact.isEmpty() && dbgender.isEmpty())) {

                tf_nic.setText(databaseNIC);
                tf_name.setText(dbfullname);
                tf_address.setText(dbaddress);
                if (dbgender == "male") {
                    rb_male.setSelected(true);
                } else {
                    rb_female.setSelected(true);
                }
                tf_contact.setText(dbcontact);
                bt_updateCustomer.setEnabled(true);
            }

            if (rb_female.isSelected()) {
                gt_gender = "male";
            } else {
                gt_gender = "female";
            }

        } catch (SQLException e) {
        }

    }//GEN-LAST:event_bt_searchActionPerformed

    private void tf_loanAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_loanAmountKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9' || c == KeyEvent.VK_PERIOD)) {
            evt.consume();
        }

    }//GEN-LAST:event_tf_loanAmountKeyTyped

    private void tf_extraInterestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_extraInterestKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9' || c == KeyEvent.VK_PERIOD)) {
            evt.consume();
        }

    }//GEN-LAST:event_tf_extraInterestKeyTyped

    private void tf_periodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_periodKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9')) {
            evt.consume();
        }

    }//GEN-LAST:event_tf_periodKeyTyped

    private void tf_contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_contactKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9' || c == KeyEvent.VK_PLUS)) {
            evt.consume();
        }

    }//GEN-LAST:event_tf_contactKeyTyped

    private void tf_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nicKeyTyped

        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9' || c == KeyEvent.VK_V)) {
            evt.consume();
        }

    }//GEN-LAST:event_tf_nicKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addLoan;
    private javax.swing.JButton bt_search;
    private javax.swing.JButton bt_updateCustomer;
    private javax.swing.JComboBox cb_mainInstallmentPeriodType;
    private javax.swing.JComboBox cb_periodType;
    public static javax.swing.JComboBox cb_selectFund;
    public static javax.swing.JComboBox cb_selectFunder_customer;
    private com.toedter.calendar.JDateChooser dc_registrationDate;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_v_finalDate;
    private javax.swing.JLabel lb_v_installment;
    private javax.swing.JLabel lb_v_loanAmount;
    private javax.swing.JLabel lb_v_period;
    private javax.swing.JLabel lb_v_profit;
    private javax.swing.JLabel lb_v_totalAmount;
    public static javax.swing.JRadioButton rb_female;
    public static javax.swing.JRadioButton rb_male;
    private javax.swing.JTable tb_customerAddView;
    public static javax.swing.JTextField tf_address;
    public static javax.swing.JTextField tf_contact;
    private javax.swing.JTextField tf_extraInterest;
    private javax.swing.JTextField tf_loanAmount;
    private javax.swing.JTextField tf_loanNumber;
    public static javax.swing.JTextField tf_name;
    public static javax.swing.JTextField tf_nic;
    private javax.swing.JTextField tf_period;
    // End of variables declaration//GEN-END:variables
//rs = MC_DB.myConnection().createStatement().executeQuery("SELECT e.funder_name, e.idfunder, u.fund, u.fund_date,u.idfund FROM funder AS e LEFT JOIN fund AS u ON e.idfunder = u.funder_idfunder;");

    private void md_loadFunder() {

        try {

            ResultSet rs;
            //rs = MC_JavaDataBaseConnection.search_AlluseTable("funder");
            cb_selectFunder_customer.removeAllItems();
            rs = MC_DB.myConnection().createStatement().executeQuery("SELECT * FROM funder ORDER BY idfunder DESC");
            while (rs.next()) {

                String funder_name = rs.getString("funder_name");
                int funder_id = rs.getInt("idfunder");
                cb_selectFunder_customer.addItem(funder_id + "-" + funder_name);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    private void loadFund(int id) {

        try {

            ResultSet rs;
            //rs = MC_JavaDataBaseConnection.search_AlluseTable("funder");
            cb_selectFund.removeAllItems();
            //rs = MC_DB.myConnection().createStatement().executeQuery("SELECT e.funder_name, e.idfunder, u.fund, u.fund_date,u.idfund FROM funder AS e LEFT JOIN fund AS u ON e.idfunder = u.funder_idfunder;");
            rs = MC_DB.myConnection().createStatement().executeQuery("SELECT * FROM fund WHERE funder_idfunder='" + id + "'  ORDER BY idfund DESC;");

            while (rs.next()) {

                String fund = rs.getString("fund");
                String funddate = rs.getString("fund_date");
                int fundid = rs.getInt("idfund");

                cb_selectFund.addItem(fundid + "-" + fund + "-" + funddate);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    private void md_genLoadId() {
//        Date datet = new Date();
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//
//        String today_date = sdf.format(datet);
        int cus_id = 0;
        int loan_id = 0;
        try {
            //String genidType = "LON-W-20160808-00001";
            String perFix = "LO";
            String periodType = "";
            if (cb_mainInstallmentPeriodType.getSelectedIndex() == 0) {
                periodType = "D";
            } else if (cb_periodType.getSelectedIndex() == 1) {
                periodType = "W";

            } else if (cb_periodType.getSelectedIndex() == 2) {
                periodType = "M";
            }

            Date date = dc_registrationDate.getDate();
            SimpleDateFormat sdff = new SimpleDateFormat("yyyy-MM-dd");
            String registration_date = sdff.format(date);
//            JOptionPane.showMessageDialog(this, "Innnnnnnnnnnnneeeeee" + registration_date + "-" + periodType);
            ResultSet rs = MC_DB.myConnection().createStatement().executeQuery("SELECT MAX(idcustomer) AS HighestID FROM customer;");
            while (rs.next()) {
                cus_id = rs.getInt("HighestID");
            }

            ResultSet rsloanid = MC_DB.myConnection().createStatement().executeQuery("SELECT MAX(idloans) AS HighestID FROM loans;");
            while (rsloanid.next()) {
                loan_id = rsloanid.getInt("HighestID");
            }

            cus_id = cus_id + 1;
            loan_id = loan_id + 1;

            String newDateRegistarion = registration_date.replaceAll("-", "");
            //JOptionPane.showMessageDialog(this, "ID is Max :" + cus_id + "----" + perFix + "-" + periodType + "-" + newDateRegistarion + cus_id);

            tf_loanNumber.setText(perFix + "-" + newDateRegistarion + "-" + cus_id + "" + periodType + "-" + loan_id);

        } catch (SQLException ex) {
            cus_id = 0;
            loan_id = 0;
            //Logger.getLogger(jp_customer_add.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public int md_funderID() {
        String idwithname = (String) cb_selectFunder_customer.getSelectedItem();
        int funderID = 0;
        try {
            String[] id = idwithname.split("-", 0);
            if (id != null) {

                funderID = Integer.parseInt(id[0]);

            } else {
                idwithname = (String) cb_selectFunder_customer.getSelectedItem();
            }
        } catch (Exception e) {
        }
        return funderID;

    }

    private void md_profitCalculation() {

        try {
            Double loanAmount = Double.parseDouble(tf_loanAmount.getText().trim());
            Double extraInterest = Double.parseDouble(tf_extraInterest.getText().trim());
            Double period = Double.parseDouble(tf_period.getText().trim());

            Double fullAmount = loanAmount + extraInterest;
            Double profit = fullAmount - loanAmount;
            Double installment = fullAmount / period;

            Long roundloanAmount = Math.round(loanAmount);
            Long roundfullAmount = Math.round(fullAmount);
            Long roundInstallment = Math.round(installment);
            Long roundProfit = Math.round(profit);

            int loanAmount_int = roundloanAmount.intValue();
            int fullAmount_int = roundfullAmount.intValue();
            int installment_int = roundInstallment.intValue();
            int Profit_int = roundProfit.intValue();
            int Period_int = period.intValue();

            String loanAmount_text = loanAmount_int + ".00";
            String fullAmount_text = fullAmount_int + ".00";
            String installment_text = installment_int + ".00";
            String Profit_text = Profit_int + ".00";
            String Period_text = Period_int + "";

            lb_v_period.setText("");
            lb_v_period.setText(Period_text);

            lb_v_totalAmount.setText("");
            lb_v_totalAmount.setText(fullAmount_text);

            lb_v_installment.setText("");
            lb_v_installment.setText(installment_text);

            lb_v_loanAmount.setText("");
            lb_v_loanAmount.setText(loanAmount_text);

            lb_v_profit.setText("");
            lb_v_profit.setText(Profit_text);

            Toolkit.getDefaultToolkit().beep();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

//    private void md_tb_loadCustomer() {
//        
//        try {
//            ResultSet rs_ldfunder = null;
//            try {
//
//                //rs = MC_JavaDataBaseConnection.myConnection().createStatement().executeQuery("");
//                rs_ldfunder = MC_DB.myConnection().createStatement().executeQuery("Select c.cus_fullname,c.cus_contact, from customer as c left join loans as l ORDER BY c.idcustomer DESC");
//
//                DefaultTableModel dtm_cus = (DefaultTableModel) tb_customerAddView.getModel();
//                dtm_cus.setRowCount(0);
//                while (rs_ldfunder.next()) {
//                    Vector v = new Vector();
//                    v.add(rs_ldfunder.getRow());
//                    v.add(rs_ldfunder.getString("c.cus_fullname"));
//                    v.add(rs_ldfunder.getString("c.cus_contact"));
//                    
//                    dtm_cus.addRow(v);
//
//                }
//
//            } catch (SQLException ex) {
//                Logger.getLogger(Admin_funderInformation.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            rs_ldfunder.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(Admin_funderInformation.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        
//        
//    }
    private void calDate() {
        if (cb_periodType.getSelectedIndex() == 1) {
            dateCounter(2);
        } else {
            dateCounter(1);
        }
    }

    private void dateCounter(int daysToSkip) {
        int dayCount = Integer.parseInt(tf_period.getText());
        Calendar cd = Calendar.getInstance();
        int day = cd.get(Calendar.DAY_OF_WEEK);
        int datediff = 0;
        if (daysToSkip == 2) {
            datediff = Calendar.SATURDAY - day;
        } else {
            datediff = Calendar.SUNDAY - day;
            if (datediff < 0) {
                datediff += 7;
            }
        }
        System.out.println(datediff);
        dayCount -= datediff;
//        dayCount -= daysToSkip;
        cd.add(Calendar.DATE, datediff);
        cd.add(Calendar.DATE, daysToSkip);
        System.out.println(cd.getTime());
        while (dayCount >= 0) {
            if (daysToSkip == 2) {
                if (cd.get(Calendar.DAY_OF_WEEK) != Calendar.SATURDAY) {
                    dayCount--;
                }
            } else if (cd.get(Calendar.DAY_OF_WEEK) != Calendar.SUNDAY) {
                dayCount--;
                System.out.println(dayCount);
            }

            cd.add(Calendar.DATE, 1);
            System.out.println(cd.getTime());
        }
        String tt_v_finalDate = cd.getTime() + "";
        String text = tt_v_finalDate;
        String[] split = text.split(" ");
        String t1 = split[0];
        String t2 = split[1];
        String t3 = split[2];
        String t4 = split[5];

        lb_v_finalDate.setText(t1 + "-" + t2 + "-" + t3 + "-" + t4);
        String notformat = t2 + "-" + t3 + "-" + t4;
        Date d = new Date(notformat);
        // JOptionPane.showMessageDialog(this, d);

    }

    private void md_tb_loadCustomer() {
        DefaultTableModel dtm;
        try {

            ResultSet rs;
            //rs = MC_JavaDataBaseConnection.search_AlluseTable("funder");
            dtm = (DefaultTableModel) tb_customerAddView.getModel();
            dtm.setRowCount(0);

            rs = MC_DB.myConnection().createStatement().executeQuery("SELECT * FROM customer ORDER BY idcustomer DESC");
            while (rs.next()) {
                int cus_id = rs.getRow();
                String cus_nic = rs.getString("cus_nic");
                String cus_name = rs.getString("cus_fullname");
                String cus_address = rs.getString("cus_address");
                String cus_contact = rs.getString("cus_contact");
                String cus_gender = rs.getString("cus_gender");

                Vector v = new Vector();
                v.add(rs.getRow());
                v.add(rs.getString("cus_nic"));
                v.add(rs.getString("cus_fullname"));
                v.add(rs.getString("cus_address"));
                v.add(rs.getString("cus_contact"));
                v.add(rs.getString("cus_gender"));
                dtm.addRow(v);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    private void md_updateCustomer() {

        try {
            if (!(localNIC.isEmpty()) && !(databaseNIC.isEmpty())) {
                if (localNIC == databaseNIC) {

                    int isOK = JOptionPane.showConfirmDialog(this, "Are you Sure Update Customer Details!", "Confrom", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    MC_DB.update_data("customer SET cus_fullname = '" + gt_fullname + "',cus_address = '" + gt_address + "',cus_contact = '" + gt_contact + "',cus_gender = '" + gt_gender + "' WHERE cus_nic = '" + gt_nic + "' ;");
                    JOptionPane.showMessageDialog(this, "Updated!");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
