/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softidea.www.public_access.user;

import com.softidea.www.private_access.adminstrator.*;
import com.softidea.www.public_access.login_user.user_login;
import com.sun.awt.AWTUtilities;
import javax.swing.JLabel;

/**
 *
 * @author deepalsuranga
 */
public class user_basicHome extends javax.swing.JFrame {

    /**
     * Creates new form admin_index
     */
    public user_basicHome() {
        initComponents();
        try {
            AWTUtilities.setWindowOpaque(this, false);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_wk_cus_add = new javax.swing.JLabel();
        jl_wk_cus_view = new javax.swing.JLabel();
        jl_wk_cus_update = new javax.swing.JLabel();
        jl_wk_cus_remove = new javax.swing.JLabel();
        jl_wk_cus_pendding = new javax.swing.JLabel();
        jl_wk_cus_close = new javax.swing.JLabel();
        pl_systemExit = new javax.swing.JPanel();
        jl_systemExit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_wk_cus_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_wk_cus_add.setForeground(new java.awt.Color(255, 255, 255));
        jl_wk_cus_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_wk_cus_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        jl_wk_cus_add.setText("Add Customer");
        jl_wk_cus_add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jl_wk_cus_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 35));

        jl_wk_cus_view.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_wk_cus_view.setForeground(new java.awt.Color(255, 255, 255));
        jl_wk_cus_view.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_wk_cus_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        jl_wk_cus_view.setText("View Customer");
        jl_wk_cus_view.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jl_wk_cus_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 150, 35));

        jl_wk_cus_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_wk_cus_update.setForeground(new java.awt.Color(255, 255, 255));
        jl_wk_cus_update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_wk_cus_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        jl_wk_cus_update.setText("Update Customer");
        jl_wk_cus_update.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jl_wk_cus_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 150, 35));

        jl_wk_cus_remove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_wk_cus_remove.setForeground(new java.awt.Color(255, 255, 255));
        jl_wk_cus_remove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_wk_cus_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        jl_wk_cus_remove.setText("Remove Customer");
        jl_wk_cus_remove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jl_wk_cus_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 150, 35));

        jl_wk_cus_pendding.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_wk_cus_pendding.setForeground(new java.awt.Color(255, 255, 255));
        jl_wk_cus_pendding.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_wk_cus_pendding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        jl_wk_cus_pendding.setText("Pendding Customer");
        jl_wk_cus_pendding.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jl_wk_cus_pendding, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 150, 35));

        jl_wk_cus_close.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_wk_cus_close.setForeground(new java.awt.Color(255, 255, 255));
        jl_wk_cus_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_wk_cus_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/public_access/images/SuneraInvestment_selctButton.png"))); // NOI18N
        jl_wk_cus_close.setText("Close Customer");
        jl_wk_cus_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jl_wk_cus_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 150, 35));

        pl_systemExit.setBackground(new java.awt.Color(33, 33, 33));
        pl_systemExit.setLayout(new java.awt.CardLayout());

        jl_systemExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_systemExit.setForeground(new java.awt.Color(255, 255, 255));
        jl_systemExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_systemExit.setText("X");
        jl_systemExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jl_systemExitMouseMoved(evt);
            }
        });
        jl_systemExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_systemExitMouseClicked(evt);
            }
        });
        pl_systemExit.add(jl_systemExit, "card2");

        getContentPane().add(pl_systemExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1275, 23, 25, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User | Work Area");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/private_access/images/frame_admin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        jPanel1.setBackground(new java.awt.Color(0, 150, 136));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 600));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softidea/www/private_access/images/under_frame.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1300, 30));

        setSize(new java.awt.Dimension(1300, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jl_systemExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_systemExitMouseMoved

        pl_systemExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        
    }//GEN-LAST:event_jl_systemExitMouseMoved

    private void jl_systemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_systemExitMouseClicked

        //System.exit(0);
        this.dispose();
        user_login uslg=new user_login();
        uslg.setVisible(true);
        
    }//GEN-LAST:event_jl_systemExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_workArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin_workArea().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_systemExit;
    private javax.swing.JLabel jl_wk_cus_add;
    private javax.swing.JLabel jl_wk_cus_close;
    private javax.swing.JLabel jl_wk_cus_pendding;
    private javax.swing.JLabel jl_wk_cus_remove;
    private javax.swing.JLabel jl_wk_cus_update;
    private javax.swing.JLabel jl_wk_cus_view;
    private javax.swing.JPanel pl_systemExit;
    // End of variables declaration//GEN-END:variables
}
