package Admins;


import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Buwaneka
 */
public class Sub_Frame extends javax.swing.JDialog {

    public int getAbc() {
        return abc;
    }

    public void setAbc(int abc) {
        this.abc = abc;
    }

    int abc;
/////////////////Load Image and Name to Confirmation///////////

    public void toconfirmation(String msg, String id,String Tab,String Id) throws Exception {
        Name.setText(msg);

        ResultSet rs = ClassFiles.DB.search("SELECT * FROM "+Tab+" WHERE "+Id+"= '" + id + "' ");
        while (rs.next()) {
            String N = rs.getString("Name");
            Loaded_Name.setText("''" + N + "'' Record ?");

            byte[] imagedata = rs.getBytes("Pic");
            Image img = Toolkit.getDefaultToolkit().createImage(imagedata);
            img = img.getScaledInstance(Loaded_Image.getHeight(), Loaded_Image.getWidth(), java.awt.Image.SCALE_SMOOTH);
            Loaded_Image.setIcon(new ImageIcon(img));

        }

    }

    /**
     * Creates new form Sub_Frame
     */
    public Sub_Frame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Loaded_Image = new javax.swing.JLabel();
        Loaded_Name = new javax.swing.JLabel();
        close_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        Name.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Name.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(Name);
        Name.setBounds(20, 104, 170, 30);
        jPanel1.add(Loaded_Image);
        Loaded_Image.setBounds(450, 84, 60, 60);

        Loaded_Name.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Loaded_Name.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(Loaded_Name);
        Loaded_Name.setBounds(190, 104, 230, 30);

        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Normal_icon_Close.png"))); // NOI18N
        close_button.setBorderPainted(false);
        close_button.setContentAreaFilled(false);
        close_button.setFocusPainted(false);
        close_button.setFocusable(false);
        close_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Revolver_icon_Close.png"))); // NOI18N
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(close_button);
        close_button.setBounds(483, 16, 30, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Normal_icon_yes.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Revolver_icon_ yes.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 160, 75, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Normal_icon_No.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Revolver_icon_ No.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 160, 75, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sub.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            abc = 10;
            this.dispose();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        abc = 20;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_close_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sub_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sub_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sub_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sub_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sub_Frame dialog = new Sub_Frame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loaded_Image;
    private javax.swing.JLabel Loaded_Name;
    private javax.swing.JLabel Name;
    private javax.swing.JButton close_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
